### ISSUE TITLE
unable to export engines h11._util.LocalProtocolError

### ISSUE THREAD

**Issue by w-e-w** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#10]
re-posting as issue post as it seems this is how you like to do things hear
example fix PR https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/pull/3
the following is copied from https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions/pull/205#issuecomment-1766334220

---

one major issue that I'm being experiencing randomly is this
it almost appear every time I try to export an engine
sometimes when this happens the process completely holds other times it continues I managed to get one successfully completed and use it to run sd with trt and I can say that it is significantly faster
but most of the time my engine fails to export, making this almost unusable

one major issue that I'm being experiencing randomly is this
it almost appear every time I try to export an engine
sometimes when this happens the process completely holds other times it continues I managed to get one successfully completed and use it to run sd with trt and I can say that it is significantly faster
but most of the time my engine fails to export, making this almost unusable
```shell
Building TensorRT engine for B:\GitHub\stable-diffusion-webui\models\Unet-onnx\Anime_Anything-V3.0_Anything-V3.0-fp16_Anything-V3.0-pruned-fp16_38c1ebe3.onnx
: B:\GitHub\stable-diffusion-webui\models\Unet-trt\Anime_Anything-V3.0_Anything-V3.0-fp16_Anything-V3.0-pruned-fp16_38c1ebe3_cc86_sample=1x4x64x64+2x4x64x64+
8x4x96x96-timesteps=1+2+8-encoder_hidden_states=1x77x768+2x77x768+8x154x768.trt
ERROR:asyncio:Exception in callback H11Protocol.timeout_keep_alive_handler()
handle: <TimerHandle when=355099.875 H11Protocol.timeout_keep_alive_handler()>
Traceback (most recent call last):
  File "B:\GitHub\stable-diffusion-webui\venv\lib\site-packages\h11\_state.py", line 249, in _fire_event_triggered_transitions
    new_state = EVENT_TRIGGERED_TRANSITIONS[role][state][event_type]
KeyError: <class 'h11._events.ConnectionClosed'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Programs\Python\3.10.6\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "B:\GitHub\stable-diffusion-webui\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 363, in timeout_keep_alive_handler
    self.conn.send(event)
  File "B:\GitHub\stable-diffusion-webui\venv\lib\site-packages\h11\_connection.py", line 468, in send
    data_list = self.send_with_data_passthrough(event)
  File "B:\GitHub\stable-diffusion-webui\venv\lib\site-packages\h11\_connection.py", line 493, in send_with_data_passthrough
    self._process_event(self.our_role, event)
  File "B:\GitHub\stable-diffusion-webui\venv\lib\site-packages\h11\_connection.py", line 242, in _process_event
    self._cstate.process_event(role, type(event), server_switch_event)
  File "B:\GitHub\stable-diffusion-webui\venv\lib\site-packages\h11\_state.py", line 238, in process_event
    self._fire_event_triggered_transitions(role, event_type)
  File "B:\GitHub\stable-diffusion-webui\venv\lib\site-packages\h11\_state.py", line 251, in _fire_event_triggered_transitions
    raise LocalProtocolError(
h11._util.LocalProtocolError: can't handle event type ConnectionClosed when role=SERVER and state=SEND_RESPONSE
```

the engines does seem to be generated (saved to disk) but the profiles are just not created so webui doesn't see it

### Cause and patch fix
as far that I can see this is caused by `yield logging_history`
I've made an edit to replace all  `yield logging_history` with `print(logging_history)` and it seems to work fine

**Comment by contentis** [comment]
As `yield` seems to be causing issues for some users it will be replaced by print and gr.Info. The changes are live on the `hot_fix` branch right now.
Currently, I don't have an ETA when this branch will be merged into the master but hopefully by end of this week latest.

**Comment by prusswan** [comment]
Re-installed the extension from `hot_fix`. For others running into similar issues, if `models/Unet-trt/mode.json` is empty or not updated, the engine build did not complete successfully

**Comment by contentis** [comment]
`hot_fix` has been merged. I'll close the issue, but feel free to reopen if you still face issues.
