### ISSUE TITLE
Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0

### ISSUE THREAD

**Issue by andreacostigliolo** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#11]
I have 2 strange error trying to use this extension  (RTX 4070) : 

1) After installation, when I start Auto1111 I get 3 times error like can't find entry point for ?destroyTensorDescriptorEx@ops@cudnn......

2) When I click to Export I get this error : ERROR:root:Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument mat1 in method wrapper_CUDA_addmm)

Thank you

**Comment by DennLie** [comment]
i get the same error.

**Comment by andreacostigliolo** [comment]
So it's fine to close this and go with your one.
