### ISSUE TITLE
"cudnn_adv_infer64_8.dll" cannot be found

### ISSUE THREAD

**Issue by Amazon90** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#114]
OS: windows 11 pro, i7-13700KF, RTX 4070ti

![螢幕擷取畫面 2023-10-23 193054](https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/assets/72290820/9ec3ba88-9e84-4022-9a7f-fd4281c1483e)
![螢幕擷取畫面 2023-10-23 193129](https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/assets/72290820/e3cb702a-88aa-4a30-b15d-7c8b86c7083b)
![螢幕擷取畫面 2023-10-23 193140](https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/assets/72290820/a70b4d7f-bc37-40ff-b98e-21d905d59efb)
![螢幕擷取畫面 2023-10-23 193152](https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/assets/72290820/71a9d995-e123-437f-a77f-155f92a1a4a2)

**Comment by Amazon90** [comment]
https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/issues/12

**Comment by LunaMorbus** [comment]
Maybe the SDXL version is not supported for the time being, please wait for
the update.

HYH-NICE ***@***.***> 于 2024年2月14日周三 下午9:15写道：

**Comment by Amazon90** [comment]
> me too  why? how to do ?

https://youtu.be/9EHCjO6GDKU
Just install the bat file in the video description bar.

**Comment by alexhegit** [comment]
me to when launch NVIDIA Chat with RTX at Windows11
