### ISSUE TITLE
[Feature request] Higher resolution than 2048

### ISSUE THREAD

**Issue by DuckersMcQuack** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#117]
I've tried to set the config json to 10000 for fun for all the max tensorRT resolutions, but it's still 2048 max in the webUI. 

So i want to request tensorRT to be whichever higher upscale resolution we desire. Or as far as our memory goes.

**Comment by contentis** [comment]
That should be an easy edit. What do you thin is reasonable, 4096?

**Comment by carnivar10** [comment]
Increasing the maximum size to 4096 seems like a good option, even if it doesn't generate up to 4096

**Comment by contentis** [comment]
The max size has been updated in the dev branch. You might need to delete the `ui-config.json` for updates to be visible.

**Comment by DuckersMcQuack** [comment]
> That should be an easy edit. What do you thin is reasonable, 4096?

Honestly? up to 10k or as high as i can go, as i wanna see how high i can convert a model to/generate with 24GB video memory and 32GB shared :D

And what's the reason behind why resolutions has to be multiplied by 64? Like, i can't do a "native 1080p", has to be 1088 for example.

**Comment by contentis** [comment]
> Honestly? up to 10k or as high as i can go, as i wanna see how high i can convert a model to/generate with 24GB video memory and 32GB shared :D

If you start swapping into shared memory, performance is going to tank, and you're probably better off using native torch.

> And what's the reason behind why resolutions has to be multiplied by 64? Like, i can't do a "native 1080p", has to be 1088 for example.

For SD the input always needs to be a multiple of 8 as the UNet works in "low-res" latent space. In this version we additionally have a requirement for the latent space to be a multiple of 8 to guarantee byte-alignment for improved memory access. And if you take 8*8 you end up with a 64x requirement in the image-space.

> and where can one manually experiment with max sizes? As i tried to change ui-configs to 10k myself on every tensorRT related setting that mentions resolutions, but didn't do anything sadly.

Here you can edit the UI options for the extension: https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/blob/main/ui_trt.py#L601C32-L651

> Or do i simply just manually download the dev release instead from the webUI :P Gonna test dev manually tomorrow and see.

There are a few ways:
1. In the extension UI you should be able to provide a branch when installing the extension. 
2. Head to the extension folder, open a shell with git and run `git fetch` followed by `git checkout dev`

But as I'm no SD power-user there might be a better way of doing things that I'm not aware of. 
<img width="962" alt="Screenshot 2023-10-26 at 09 01 29" src="https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/assets/29352092/8bc9fc78-acac-4f79-b133-9c519a386790">

*Note:* The dev branch might have bugs.

**Comment by DuckersMcQuack** [comment]
Is it ok if i can ask general questions within this thread? Or new "open" one per question for other not relevant to main topic?

Cause i was wondering if tensorRT is capable of doing multi gpu generations, or split workload across 2 3090's for instance? Or does that not work for tensorRT? Mostly for doubling my performance even more, but also for splitting the high memory demand for making past 2048 TRT models for upscales :P
