### ISSUE TITLE
Unable to export TRT model file : ERROR:root:Failed to save engine: [Errno 2] No such file or directory:

### ISSUE THREAD

**Issue by SebastianBeck369** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#122]
I have been trying to generate a trt file for this checkpoint merge. It seems to export the .onnx file and a build trt engine but apparently not a .trt save file and therefore it fails to save the engine as the file is never created in the first place...??? This has worked for a similiar sort of checkpoint merge of similiar size. 

Is this error due to this tensor to python boolean conversion?

Any hints or pointers would be appreciated.

Exporting 0.5(abyssorangemix2_Hard) + 0.5(ambientgrapemixAnime2D_v20) to TensorRT
{'sample': [(1, 4, 64, 64), (2, 4, 64, 64), (8, 4, 96, 96)], 'timesteps': [(1,), (2,), (8,)], 'encoder_hidden_states': [(1, 77, 768), (2, 77, 768), (8, 154, 768)]}
No ONNX file found. Exporting ONNX...
Disabling attention optimization
C:\Users\Omen\Desktop\Engineering\Programming\AI\stable-diffusion-webui\venv\Lib\site-packages\einops\einops.py:314: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  known = {axis for axis in composite_axis if axis_name2known_length[axis] != _unknown_axis_length}
C:\Users\Omen\Desktop\Engineering\Programming\AI\stable-diffusion-webui\venv\Lib\site-packages\einops\einops.py:315: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  unknown = {axis for axis in composite_axis if axis_name2known_length[axis] == _unknown_axis_length}
C:\Users\Omen\Desktop\Engineering\Programming\AI\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\openaimodel.py:158: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert x.shape[1] == self.channels
C:\Users\Omen\Desktop\Engineering\Programming\AI\stable-diffusion-webui\modules\sd_hijack_unet.py:26: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if a.shape[-2:] != b.shape[-2:]:
C:\Users\Omen\Desktop\Engineering\Programming\AI\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\openaimodel.py:109: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert x.shape[1] == self.channels
============= Diagnostic Run torch.onnx.export version 2.0.1+cu118 =============
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

[I] Folding Constants | Pass 1
[I]     Total Nodes | Original:  8992, After Folding:  6216 |  2776 Nodes Folded
[I] Folding Constants | Pass 2
[I]     Total Nodes | Original:  6216, After Folding:  4968 |  1248 Nodes Folded
[I] Folding Constants | Pass 3
[I]     Total Nodes | Original:  4968, After Folding:  4968 |     0 Nodes Folded
Exported to ONNX.
Building TensorRT engine... This can take a while, please check the progress in the terminal.
Building TensorRT engine for C:\Users\Omen\Desktop\Engineering\Programming\AI\stable-diffusion-webui\models\Unet-onnx\0.5(abyssorangemix2_Hard) + 0.5(ambientgrapemixAnime2D_v20)_06ace631.onnx: C:\Users\Omen\Desktop\Engineering\Programming\AI\stable-diffusion-webui\models\Unet-trt\0.5(abyssorangemix2_Hard) + 0.5(ambientgrapemixAnime2D_v20)_06ace631_cc86_sample=1x4x64x64+2x4x64x64+8x4x96x96-timesteps=1+2+8-encoder_hidden_states=1x77x768+2x77x768+8x154x768.trt
[libprotobuf WARNING **************************************************************************\externals\protobuf\3.0.0\src\google\protobuf\io\coded_stream.cc:604] Reading dangerously large protocol message.  If the message turns out to be larger than 2147483647 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING **************************************************************************\externals\protobuf\3.0.0\src\google\protobuf\io\coded_stream.cc:81] The total number of bytes read was 1721604346
[libprotobuf WARNING **************************************************************************\externals\protobuf\3.0.0\src\google\protobuf\io\coded_stream.cc:604] Reading dangerously large protocol message.  If the message turns out to be larger than 2147483647 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING **************************************************************************\externals\protobuf\3.0.0\src\google\protobuf\io\coded_stream.cc:81] The total number of bytes read was 1721604346
[I] Loading tactic timing cache from C:\Users\Omen\Desktop\Engineering\Programming\AI\stable-diffusion-webui\extensions\Stable-Diffusion-WebUI-TensorRT\timing_caches\timing_cache_win_cc86.cache
[I] Building engine with configuration:
    Flags                  | [FP16, REFIT, TF32]
    Engine Capability      | EngineCapability.DEFAULT
    Memory Pools           | [WORKSPACE: 8191.50 MiB, TACTIC_DRAM: 8191.50 MiB]
    Tactic Sources         | [CUBLAS, CUDNN, EDGE_MASK_CONVOLUTIONS, JIT_CONVOLUTIONS]
    Profiling Verbosity    | ProfilingVerbosity.LAYER_NAMES_ONLY
    Preview Features       | [FASTER_DYNAMIC_SHAPES_0805, DISABLE_EXTERNAL_TACTIC_SOURCES_FOR_CORE_0805]
Building engine: 100%|███████████████████████████████████████████████████████████████████| 6/6 [01:52<00:00, 18.67s/it]
[I] Finished engine building in 113.046 seconds
[I] Saving tactic timing cache to C:\Users\Omen\Desktop\Engineering\Programming\AI\stable-diffusion-webui\extensions\Stable-Diffusion-WebUI-TensorRT\timing_caches\timing_cache_win_cc86.cache
[I] Saving engine to C:\Users\Omen\Desktop\Engineering\Programming\AI\stable-diffusion-webui\models\Unet-trt\0.5(abyssorangemix2_Hard) + 0.5(ambientgrapemixAnime2D_v20)_06ace631_cc86_sample=1x4x64x64+2x4x64x64+8x4x96x96-timesteps=1+2+8-encoder_hidden_states=1x77x768+2x77x768+8x154x768.trt
ERROR:root:Failed to save engine: [Errno 2] No such file or directory: 'C:\\Users\\Omen\\Desktop\\Engineering\\Programming\\AI\\stable-diffusion-webui\\models\\Unet-trt\\0.5(abyssorangemix2_Hard) + 0.5(ambientgrapemixAnime2D_v20)_06ace631_cc86_sample=1x4x64x64+2x4x64x64+8x4x96x96-timesteps=1+2+8-encoder_hidden_states=1x77x768+2x77x768+8x154x768.trt'

**Comment by contentis** [comment]
Windows has a limitation on the path length of 256 characters. And `C:\Users\Omen\Desktop\Engineering\Programming\AI\stable-diffusion-webui\models\Unet-trt\0.5(abyssorangemix2_Hard) + 0.5(ambientgrapemixAnime2D_v20)_06ace631_cc86_sample=1x4x64x64+2x4x64x64+8x4x96x96-timesteps=1+2+8-encoder_hidden_states=1x77x768+2x77x768+8x154x768.trt`
is 268 long. Either you need to move the project to a different path or enable long paths in Windows: https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry#enable-long-paths-in-windows-10-version-1607-and-later
