### ISSUE TITLE
Minimal Resolutions

### ISSUE THREAD

**Issue by Krischan68** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#135]
Hey, 
creating TensorRT SDXL engines with min resolution 640 in height and width is possible. Using these engines leads to errors. Would it be possible to change the min width and min height for SDXL to 640? Would be nice e.g. for full body shots and decrease time.
Thank you.

**Comment by wizz13150** [comment]
Hey, i'm using 2 dynamic engines from 448 to 2048 without any issue.
To allow both adetailer and hires with the same engine per model.
Created with a rtx3060 12gb.

To build an engine, be sure :
- to not have a trt unet currently loaded.
- to not use `--lowvram` (maybe --medvram, not sure)

You'll run into errors in these situations. So just run the webui, switch to 'None' without loading any trt engine, go to the trt tab and create your engine.

Cheers ! 🥂

**Comment by wizz13150** [comment]
Hey, if you created the engine, it should be fine.

I'm using a single engine per model, from 448 to 2048, to allow adetailer and hires x1.5
Created with a 3060 12gb.

Be sure to not use the Negative Guidance, it will crash when the NG comes in. 
Probably the same for some settings.
You can rename your `ui-config.json` and run again the webui.

Cheers ! 🥂

**Comment by Krischan68** [comment]
It works, Thank you very much.
