### ISSUE TITLE
Unable to export default engine

### ISSUE THREAD

**Issue by mojack411** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#136]
It looks like there were some similar issues reported but none of them seemed like quite the same as mine so I figured I'd make a new thread. I'm having difficulty exporting the default TRT Engine. An earlier issue identified a --medvram commandline argument was the cause but I don't have that argument in my webui file. Not sure what's going on here so help would be appreciated. Apologies in advance if it's something silly and simple that I overlooked.

venv "C:\Users\User\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: v1.5.1
Commit hash: 68f336bd994bed5442ad95bad6b6ad5564a5409a

Launching Web UI with arguments: --gradio-img2img-tool color-sketch --xformers
Loading weights [812cd9f9d9] from C:\Users\User\stable-diffusion-webui\models\Stable-diffusion\anythingV3_fp16.ckpt
Creating model from config: C:\Users\User\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading VAE weights specified in settings: C:\Users\User\stable-diffusion-webui\models\Stable-diffusion\nai.vae.pt
Applying attention optimization: xformers... done.
Model loaded in 4.3s (load weights from disk: 1.2s, create model: 0.4s, apply weights to model: 0.5s, apply half(): 0.7s, load VAE: 0.5s, move model to device: 0.7s, calculate empty prompt: 0.1s).
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 14.7s (launcher: 2.8s, import torch: 3.1s, import gradio: 0.8s, setup paths: 0.7s, other imports: 0.9s, load scripts: 1.6s, create ui: 4.5s, gradio launch: 0.1s).
INFO:httpx:HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"
Exporting anythingV3_fp16 to TensorRT
{'sample': [(1, 4, 64, 64), (2, 4, 64, 64), (8, 4, 96, 96)], 'timesteps': [(1,), (2,), (8,)], 'encoder_hidden_states': [(1, 77, 768), (2, 77, 768), (8, 154, 768)]}
No ONNX file found. Exporting ONNX...
Traceback (most recent call last):
  File "C:\Users\Matthew Ponthier\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\Matthew Ponthier\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "C:\Users\Matthew Ponthier\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\Matthew Ponthier\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\Matthew Ponthier\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\Matthew Ponthier\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\Matthew Ponthier\stable-diffusion-webui\extensions\Stable-Diffusion-WebUI-TensorRT\ui_trt.py", line 134, in export_unet_to_trt
    gr.Info("No ONNX file found. Exporting ONNX...  Please check the progress in the terminal.")
AttributeError: module 'gradio' has no attribute 'Info'
INFO:httpx:HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 500 Internal Server Error"
INFO:httpx:HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"

**Comment by chazzhou** [comment]
You are running v1.5.1, an old version of Automatic1111 (currently 1.6.0). Do a `git pull` under the Automatic1111 root folder and relaunch. It should update the dependencies automatically. However, if it doesn't and you are still getting the same error you need to run `pip install --upgrade gradio`.

**Comment by mojack411** [comment]
Thank you! I figured it would probably be something simple like that. Was able to export the engine no problem now.
