### ISSUE TITLE
Model Conversion failing: ERROR:root:Failed to build engine: Invalid Engine

### ISSUE THREAD

**Issue by wogam** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#139]
> Exporting PWJ_Plus.fp16 to TensorRT
> {'sample': [(1, 4, 112, 112), (1, 4, 149, 112), (8, 4, 149, 149)], 'timesteps': [(1,), (1,), (8,)], 'encoder_hidden_states': [(1, 231, 2048), (1, 231, 2048), (8, 308, 2048)], 'y': [(1, 2816), (1, 2816), (8, 2816)]}
> Building TensorRT engine... This can take a while, please check the progress in the terminal.
> Building TensorRT engine for C:\stable-diffusion-webui\models\Unet-onnx\PWJ_Plus.fp16_96b6e7aa.onnx: C:\stable-diffusion-webui\models\Unet-trt\PWJ_Plus.fp16_96b6e7aa_cc86_sample=1x4x112x112+1x4x149x112+8x4x149x149-timesteps=1+1+8-encoder_hidden_states=1x231x2048+1x231x2048+8x308x2048-y=1x2816+1x2816+8x2816.trt
> [I] Loading tactic timing cache from C:\stable-diffusion-webui\extensions\Stable-Diffusion-WebUI-TensorRT\timing_caches\timing_cache_win_cc86.cache
> [I] Building engine with configuration:
>     Flags                  | [FP16, REFIT, TF32]
>     Engine Capability      | EngineCapability.DEFAULT
>     Memory Pools           | [WORKSPACE: 24575.50 MiB, TACTIC_DRAM: 24575.50 MiB]
>     Tactic Sources         | [CUBLAS, CUDNN, EDGE_MASK_CONVOLUTIONS, JIT_CONVOLUTIONS]
>     Profiling Verbosity    | ProfilingVerbosity.LAYER_NAMES_ONLY
>     Preview Features       | [FASTER_DYNAMIC_SHAPES_0805, DISABLE_EXTERNAL_TACTIC_SOURCES_FOR_CORE_0805]
> Building engine:  50%|█████████████████████████████████████████████████▌                                                 | 3/6 [00:02<00:00,  8.53it/s][E] 4: kOPT values for profile 0 violate shape constraints: /Concat_4: axis 2 dimensions must be equal for concatenation on axis 1. Condition '==' violated: 76 != 75.
> Building engine: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.83it/s]
> [E] 4: [shapeCompiler.cpp::nvinfer1::builder::DynamicSlotBuilder::evaluateShapeChecks::1311] Error Code 4: Internal Error (kOPT values for profile 0 violate shape constraints: /Concat_4: axis 2 dimensions must be equal for concatenation on axis 1. Condition '==' violated: 76 != 75.)
> [!] Invalid Engine. Please ensure the engine was built correctly
> ERROR:root:Failed to build engine: Invalid Engine. Please ensure the engine was built correctly

452.39 drivers

**Comment by wogam** [comment]
Edit: the resolutions need to be divisible by 64.

**Comment by bigmover** [comment]
> Edit: the resolutions need to be divisible by 64.


You mean the ‘Dynamic’ shape engine must be multiply  of 64？
