### ISSUE TITLE
Installing on Auto1111 (1.6.0) hangs forever, then WebUI doesn't start

### ISSUE THREAD

**Issue by Gyramuur** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#14]
When installing through the extensions tab via the URL as suggested, it gets stuck at "installing" for several minutes and the console never indicates that it's doing anything.

When installing manually via git clone in the extensions folder, it will install quickly without problem, but then WebUI won't launch and hangs at the "commit hash" step:

venv "E:\webui2\new\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)]
Version: v1.6.0
Commit hash: 5ef669de080814067961f28357256e8fe27544f4

**Comment by Gavr728** [comment]
same

**Comment by racerx2oo3** [comment]
If the folder stable-diffusion-webui-tensorrt exists in the extensions folder, delete it and restart the webui

**Comment by Gyramuur** [comment]
> If the folder stable-diffusion-webui-tensorrt exists in the extensions folder, delete it and restart the webui

Yeah that allows me to use WebUI, but I also want to use the extension, lol

**Comment by Alphyn-gunner** [comment]
The extension installs A LOT of dependencies. Expect to wait 10 minutes or more depending on your internet connection. Just delete the folder and try reinstalling it, it should go faster in fact because of the pip cache.

**Comment by Gyramuur** [comment]
> The extension installs A LOT of dependencies. Expect to wait 10 minutes or more depending on your internet connection. Just delete the folder and try reinstalling it, it should go faster in fact because of the pip cache.

Thanks, wasn't expecting it to take that long but after waiting ~20 minutes it eventually installed. Now I'm getting the multiple "procedure entry point" errors that occur with #12 

But after clicking through them, the extension functions normally.
