### ISSUE TITLE
I'm not able to generate profiles other than default - stuck at 19/XXX

### ISSUE THREAD

**Issue by PaoloNeoz** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#149]
Hi !
I'm not able to generate profiles other than default ... the process stops here (see below) and nothing happens then ...
The GPU remains under heavy load as you can see below.
In this example I was trying to generate 768*768 static for cyberrealistic v33 but it happens with other models too.

![Screenshot 2023-11-03 145258](https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/assets/148328647/13ec0d05-743c-4963-8ddc-087575f08cc2)
![Screenshot 2023-11-03 145536](https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/assets/148328647/acae39e9-f605-43db-8ffa-b5f3ca654ed1)

Thanks in advance for a suggestion for a possible solution :-)
Paolo

**Comment by MorkTheOrk** [comment]
Hey! How long did you wait for the engine generation? Depending on the configuration, it might take longer.

**Comment by PaoloNeoz** [comment]
> Hey! How long did you wait for the engine generation? Depending on the configuration, it might take longer.

Yes I waited for quite a long period, and it stops at 19/472.
I'm expecting to complete the task in the same amount of time of default profile.
In the past I managed to create a profile for 768 in a reasonable amount of time, but it's not the case anymore. 
:-(

**Comment by MorkTheOrk** [comment]
Does it work with SD1.5?

**Comment by PaoloNeoz** [comment]
I'm only trying with 1.5 models

**Comment by murkinhustla** [comment]
I have almost the exact same thing happening.

**Comment by contentis** [comment]
Closing as this seems to have been resolved. Sorry for the inconvenience, but sometimes TensorRT can be a bit funky when encountering unknown models.
