### ISSUE TITLE
Dynamic engine is poor performance

### ISSUE THREAD

**Issue by thanayut1750** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#152]
without TensorRT
![image](https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/assets/28057767/667b528d-1e88-413d-bf92-c8e241052c41)

with TensorRT dynamic engine
![image](https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/assets/28057767/8f598b09-bf66-4a11-81c2-73bb18d922e3)

**Comment by thanayut1750** [comment]
> What GPU are you using? Have you tried static shaped engines to compare the performance?

- RTX 3060 6GB of VRAM
- yes, I tried that static engine look good for me but still see some bug that some time even you have the MATCH profile for specific resolution (another static profile kinna give up on Dynamic profile for now )it will say "Profile not Found"

**Comment by stephenfung98** [comment]
getting the same thing on 4080, SDXL

4.98 it/s without TensorRT
1.2-1.4 it/s with TesnorRT

![Screenshot 2023-11-06 211739](https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/assets/22733057/ff971e16-a657-423c-b34b-796387fd53a3)

**Comment by stephenfung98** [comment]
4.98 it/s without TensorRT
~12-13 it/s with TesnsorRT

doing a fresh install helped.
nvidia control panel -> power management mode -> prefer maximum performance helped
https://nvidia.custhelp.com/app/answers/detail/a_id/5490 this helped
windows settings -> system -> display -> graphics -> change custom default graphics system settings -> off for Hardware Accelerated GPU Scheduling

9.1 GB dedicated gpu memory at idle.
maxing around 11 GB of dedicated gpu memory when generating 1 image, 768x768, 30 steps, sdxl

**Comment by thanayut1750** [comment]
> Its possible that the 6GB VRAM is the limiting factor, what driver are you using? Could you make a screenshot of the VRAM usage (or general GPU usage) for Task manager (if you use windows).

yeah from where i test it is likely to be that 6GB of vram cann't afford for SDXL engine generation it gave "Out of Memory" all  the time when i try to build SDXL engine but I hope the team make it possible for now ill play 1.5 model with static engine profile instead 😒

**Comment by giovanith** [comment]
same problem here: RTX 4090 perform 5 to 7 times slower to create an image with TRT 'activated' (sdxl, 1024*768).
...no miracles for while...

**Comment by contentis** [comment]
The VRAM consumption during build time is an issue... You could try getting a prebuild engine from another user and see if that works... For now I won't be able to post anything precompiled.
