### ISSUE TITLE
Is TensorRT not compatible with ControlNet?

### ISSUE THREAD

**Issue by resautu** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#153]
When I use ControlNet, terminal will tell me  "RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument mat1 in method wrapper_CUDA_addmm)", so is TensorRT not compatible with ControlNet?

**Comment by worksforme** [comment]
It is not compatible yet. There is an existing issue https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/issues/66 to track it.
