### ISSUE TITLE
ModuleNotFoundError: No module named 'importlib_metadata'

### ISSUE THREAD

**Issue by Jonseed** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#157]
I installed the extension when it first came out, and it was working, but now it gives this error when I start the webui server. What does this mean, and how do I fix it?

```
*** Error running install.py for extension D:\repos\stable-diffusion-webui\extensions\Stable-Diffusion-WebUI-TensorRT.
*** Command: "d:\repos\stable-diffusion-webui\venv\Scripts\python.exe" "D:\repos\stable-diffusion-webui\extensions\Stable-Diffusion-WebUI-TensorRT\install.py"
*** Error code: 1
*** stderr: Traceback (most recent call last):
***   File "D:\repos\stable-diffusion-webui\extensions\Stable-Diffusion-WebUI-TensorRT\install.py", line 2, in <module>
***     from importlib_metadata import version
*** ModuleNotFoundError: No module named 'importlib_metadata'
```

**Comment by Jonseed** [comment]
ChatGPT recommends changing the line `from importlib_metadata import version` to `from importlib.metadata import version`, replacing the underscore with a period?

**Comment by KNARZ0R** [comment]
I fixed the issue with this command:

`/PATH_TO_YOUR/stable-diffusion-webui/venv/bin/python3 -m pip install importlib_metadata`

**Comment by Jonseed** [comment]
Yeah, I just activated the venv and then `pip install importlib_metadata` and the error went away. But it looks like importlib_metadata is a library for users on Python versions lower than 3.8. If you have Python 3.8 or higher, then you shouldn't need importlib_metadata, and should use importlib.metadata instead, since it is included in the standard library in Python. Since Stable Diffusion recommends using Python 3.10.6, this line in the extension should probably be changed to importlib.metadata.
