### ISSUE TITLE
error while saving engine 

### ISSUE THREAD

**Issue by kotaxyz** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#160]
Building TensorRT engine... This can take a while, please check the progress in the terminal.
Building TensorRT engine for I:\stable-diffusion-1.6\stable-diffusion-1.6\models\Unet-onnx\sd_xl_base_1.0_0.9vae_be9edd61.onnx: I:\stable-diffusion-1.6\stable-diffusion-1.6\models\Unet-trt\sd_xl_base_1.0_0.9vae_be9edd61_cc86_sample=2x4x96x96+2x4x128x128+8x4x144x160-timesteps=2+2+8-encoder_hidden_states=2x77x2048+2x77x2048+8x77x2048-y=2x2816+2x2816+8x2816.trt
[W] CUDA lazy loading is not enabled. Enabling it can significantly reduce device memory usage and speed up TensorRT initialization. See "Lazy Loading" section of CUDA documentation https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#lazy-loading
[I] Loading tactic timing cache from I:\stable-diffusion-1.6\stable-diffusion-1.6\extensions\Stable-Diffusion-WebUI-TensorRT\timing_caches\timing_cache_win_cc86.cache
[I] Building engine with configuration:
    Flags                  | [FP16, REFIT, TF32]
    Engine Capability      | EngineCapability.DEFAULT
    Memory Pools           | [WORKSPACE: 8191.38 MiB, TACTIC_DRAM: 8191.38 MiB]
    Tactic Sources         | [CUBLAS, CUDNN, EDGE_MASK_CONVOLUTIONS, JIT_CONVOLUTIONS]
    Profiling Verbosity    | ProfilingVerbosity.LAYER_NAMES_ONLY
    Preview Features       | [FASTER_DYNAMIC_SHAPES_0805, DISABLE_EXTERNAL_TACTIC_SOURCES_FOR_CORE_0805]
Building engine:  50%|█████████████████████████████████▌                                 | 3/6 [00:02<00:00,  6.67it/s][W] UNSUPPORTED_STATESkipping tactic 0 due to insufficient memory on requested size of 11442586624 detected for tactic 0x0000000000000000. costs:   0%|                                                                   | 0/5 [00:00<?, ?it/s]
Building engine: 100%|██████████████████████████████████████████████████████████████████| 6/6 [19:24<00:00, 194.15s/it]
[I] Finished engine building in 1172.786 seconds
[I] Saving tactic timing cache to I:\stable-diffusion-1.6\stable-diffusion-1.6\extensions\Stable-Diffusion-WebUI-TensorRT\timing_caches\timing_cache_win_cc86.cache
ERROR:root:Failed to save engine:

**Comment by Legendaryl123** [comment]
I'm getting the same issue on an RTX 4050 when trying to build engines for SDXL, also.  I'm experimenting with command line arguments to see if I can get it to avoid the same error.  You may try to add "set CUDA_MODULE_LOADING=LAZY" in your webui-user.bat file in any line above the "set COMMANDLINE_ARGS=" to take care of that "lazy loading error" in the top part of your posted output.  That may free up enough VRAM for the task to complete.
To be honest, I think those of us with this error may have to edit some python in the TensorRT files to shrink the memory pool size so we don't get overflows like this.  I'm not versed in this stuff at all and learning as I go.  
Thinking some magic use of the command " –-memPoolSize=<pool_spec>" and changing things below a certain threshold, might get things over the hump.
Not sure where to implement that command or what pool size to set, but people training LLMs are running into this error as well and getting it resolved.
Hope this helps or at least bumps the comment

**Comment by contentis** [comment]
@kotaxyz this is an issue with Windows having a limit on path lengths... https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/issues/122#issuecomment-1779378079

**Comment by AmmBe** [comment]
Try increasing the virtual memory, it helped me solve this problem. I had 32 GB of RAM and 10 GB of virtual and this was not enough.

**Comment by GeniusBroccoli** [comment]
> Try increasing the virtual memory, it helped me solve this problem. I had 32 GB of RAM and 10 GB of virtual and this was not enough.

I can confirm, I have this error and increasing limit on path lengths not help for me. Changing heap size to auto solve issue. Thanks.
