### ISSUE TITLE
Poor performance when TRT activated (dynamic engine)

### ISSUE THREAD

**Issue by giovanith** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#167]
Hello,

I have a RTX 4090, and running webui with sdxl on Windows 10. 40 Gb Ram.
To generate an image (1024 x 768) with TRT not activated it took 4.8 sec. My prompt was a simple "a book on the table", 20 steps, 'Euler a'.
When I activate TRT [sd_xl_base_1.0] it took 38.9 sec (1st time), and 25.2 sec (2º time). It is 7 to 5 times longer!!!

At least for me TensorRT extension does not run as expected. Any clue about ?

Thanks

**Comment by giovanith** [comment]
thank you,

I created a 'fixed' tensor and it run as expected. Around 40% improvement in speed. Another good new is the new Lora to use LCM...
It worth a try.

**Comment by contentis** [comment]
Closing as this seems to be resolved. Feel free to reopen if additional help is required.
