### ISSUE TITLE
How to use ControlNet?

### ISSUE THREAD

**Issue by FlamingJay** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#171]
hi, I have found the variable controlnet in the func 'export_unet_to_trt'.  How to use it? Any demo?

**Comment by contentis** [comment]
Currently, there is no way to use ControlNet, but I'm scoping to have a "alpha" in the near future. The controlnet code you can currently see in the codebase is a relict from https://github.com/NVIDIA/TensorRT/tree/main/demo/Diffusion which this extension is based of. 
If you want to give TensorRT + ControlNet a spin, this is probably the best place at the moment, but it will be fairly limited in terms of functionality.

**Comment by FlamingJay** [comment]
> Currently, there is no way to use ControlNet, but I'm scoping to have a "alpha" in the near future. The controlnet code you can currently see in the codebase is a relict from https://github.com/NVIDIA/TensorRT/tree/main/demo/Diffusion which this extension is based of. If you want to give TensorRT + ControlNet a spin, this is probably the best place at the moment, but it will be fairly limited in terms of functionality.

thanks. I am also trying on thie issue.

**Comment by bigmover** [comment]
> Currently, there is no way to use ControlNet, but I'm scoping to have a "alpha" in the near future. The controlnet code you can currently see in the codebase is a relict from https://github.com/NVIDIA/TensorRT/tree/main/demo/Diffusion which this extension is based of. If you want to give TensorRT + ControlNet a spin, this is probably the best place at the moment, but it will be fairly limited in terms of functionality.

Controlnet is enabled with TensorRT?
