### ISSUE TITLE
Minimum NVIDIA driver requirement (Linux) for TensorRT acceleration

### ISSUE THREAD

**Issue by zopieux** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#19]
Hi,

Which minimum driver version is required for TensorRT support on Linux? The README is quite terse on requirements. My setup is currently:

    Driver Version: 535.113.01   CUDA Version: 12.2

While “exporting the engines” seems to work fine, and I'm seeing an obvious performance increase, it's unclear if updating the driver is actually required.

Thanks.

**Comment by IdiotSandwichTheThird** [comment]
I checked on windows, and don't see much of a performance increase switching drivers.

TensorRT+545.84 driver: 02:31, 1.52s/it

TensorRT+531.18 driver: 02:36, 1.57s/it

**Comment by zopieux** [comment]
I can report that without any driver update (still 535.113.01), this extension manages to accelerate my RTX 4090 from <5it/s to >16it/s (dynamic engine, SD 1.5). Not bad!

**Comment by kopyl** [comment]
@zopieux strange. I was able to get 25it/s speed from A1111 (sd 1.5) without this extension.

Do we have NVIDIA devs here? Are there going to be drivers provided for Linux for this thing to work? Also instructions on how to install those. Please don't say you make everything for Windows first, that would be dumb.

**Comment by contentis** [comment]
The driver should be less relevant for performance. We always recommend using the latest driver for general performance improvements, but are the kernels being generated by TensorRT.

The only requirements on the driver are imposed by CUDA. TensorRT 9.x (used in this plugin) required CUDA > 11.0. Therefore, any driver that supports CUDA>11.0 should work fine. 
I'll add the driver / cuda requirement to the readme.

**Comment by contentis** [comment]
The Readme has been updated now with some more information. I'll close this issue, but feel free to reopen if you think there is still something missing or you encounter further issues.
