### ISSUE TITLE
Internal Error (Concat_7812: axis 2 dimensions must be equal for concatenation on axis 1. Condition '==' violated: 87 != 88.

### ISSUE THREAD

**Issue by FlamingJay** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#190]
hey, i have got a problem when using tensorrt sd_webui.

I want to generate a image with shape (height: 703, width: 512). In fact it will generate an image with shape (696, 512) in original sd_webui. because 703 // 8 * 8 == 696 and 512 //8 * 8 == 512.

Then i try it on tensorRT with **dynamic** mode. However it occurs 

'''
[E] 7: [shapeMachine.cpp::executeContinuation::887] Error Code 7: Internal Error (Concat_7812: axis 2 dimensions must be equal for concatenation on axis 1. Condition '==' violated: 87 != 88. Instruction: CHECK_EQUAL 87 88.)
'''

After some tries, I found the height and width should be such as 512\~519, 576\~583, 640\~647, 704\~711, 768\~775.

We can understand in this way:

512\~519 // 8  = 64
576\~583 // 8  = 72 = 64 + 8
640\~647 // 8 = 80 = 64 + 8 * 2
704\~711 // 8 = 88 = 64 + 8 * 3
768\~775 // 8 = 96 = 64 + 8 * 4

the TRT unet is in dynamic mode,
![image](https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/assets/29722493/170b38db-d927-4b88-8703-1c44354620a8)

**however, ths static mode works.**

Is there any solution to generate other shapes under dynamic mode?

**Comment by FlamingJay** [comment]
env:

torch                     1.12.1+cu116
pytorch-lightning         1.9.4

tensorrt                  9.0.1.post11.dev4
tensorrt-bindings         9.0.1.post11.dev4
tensorrt-libs             9.0.1.post11.dev4

onnx                      1.15.0
onnx-graphsurgeon         0.3.27
onnxruntime-gpu           1.16.3

cupy-cuda11x              12.2.0


nvidia-cublas-cu11        2022.4.8
nvidia-cublas-cu117       11.10.1.25
nvidia-cuda-runtime-cu11  2022.4.25
nvidia-cuda-runtime-cu117 11.7.60
nvidia-cudnn-cu11         2022.5.19
nvidia-cudnn-cu116        8.4.0.27

**Comment by bigmover** [comment]
The problem is solved? or figured out what problem is it ?

**Comment by FlamingJay** [comment]
> The problem is solved? or figured out what problem is it ?

没有找到根本原因，只能定位到是推理时的shape不是64的倍数导致的。
解决的办法，试出来一个，就是生成engine的过程中，将opt_height和opt_width设为非64的倍数，比如(666, 555)这种
