### ISSUE TITLE
Why the resolution needs to be a multiple of 64?

### ISSUE THREAD

**Issue by FlamingJay** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#192]
I have a question the resolution needs to be a multiple of 64.

the original sd_webui support any resolution within 64 to 2048

**Comment by FurkanGozukara** [comment]
ye that is super restrictive

**Comment by J-Cott** [comment]
> ye that is super restrictive

Oh no, I only have these resolutions to pick from:
64
128
192
256
320
384
448
512
576
640
704
768
832
896
960
1024
1088
1152
1216
1280
1344
1408
1472
1536
1600
1664
1728
1792
1856
1920
1984
2048
2112
2176
2240
2304
2368
2432
2496
2560
!

**Comment by FurkanGozukara** [comment]
The problem occurs when you do high res fix

Try and see

**Comment by J-Cott** [comment]
I usually do a 2x or 2.5x upscale on 1024x1024 images, that works fine. Or just find the nearest number that is a multiple of 64.

**Comment by FurkanGozukara** [comment]
> I usually do a 2x or 2.5x upscale on 1024x1024 images, that works fine. Or just find the nearest number that is a multiple of 64.

that is being very hard when you dont use square base

lets imagine 1344x768

**Comment by contentis** [comment]
The multiple of 64 occurs due to optimized memory reads, allowing optimal cache utilisation. This won't be "fixed" - the only thing that would be possible is using padding but that comes at a cost for unnecessary compute.

**Comment by FurkanGozukara** [comment]
> The multiple of 64 occurs due to optimized memory reads, allowing optimal cache utilisation. This won't be "fixed" - the only thing that would be possible is using padding but that comes at a cost for unnecessary compute.

I see thanks for reply. When we can expect controlnet?

**Comment by FlamingJay** [comment]
> > The multiple of 64 occurs due to optimized memory reads, allowing optimal cache utilisation. This won't be "fixed" - the only thing that would be possible is using padding but that comes at a cost for unnecessary compute.
> 
> I see thanks for reply. When we can expect controlnet?

a new branch named controlnet is already presented by @contentis . you can try it. 

Besides, I recently develop a method that uses original [sd-webui-controlnet](https://github.com/Mikubill/sd-webui-controlnet) but replace original pt model with new engine, which also works well.

**Comment by FurkanGozukara** [comment]
> Besides, I recently develop a method that uses original [sd-webui-controlnet](https://github.com/Mikubill/sd-webui-controlnet) but replace original pt model with new engine, which also works well.

i tried dev and it gave me errors - unuseable

how this new method works?

**Comment by contentis** [comment]
@FurkanGozukara, the controlnet branch is far from ready, and I don't have an ETA yet. For now I concentrated on getting the existing stuff working well, especially the LoRA part (v0.2.0). ControlNet will be a non backward-compatabile break  therefore I want to try to make it flexible enough to not break in the near future again. 

@FlamingJay can you provide details on how your method works?

**Comment by FlamingJay** [comment]
> @FurkanGozukara, the controlnet branch is far from ready, and I don't have an ETA yet. For now I concentrated on getting the existing stuff working well, especially the LoRA part (v0.2.0). ControlNet will be a non backward-compatabile break therefore I want to try to make it flexible enough to not break in the near future again.
> 
> @FlamingJay can you provide details on how your method works?

hi, I just upload my implementation at [tensorrt_control_lora](https://github.com/FlamingJay/Stable-Diffusion-WebUI-TensorRT/tree/control_lora). This method is a bit cumbersome.  Read the info.md first.

**Comment by FurkanGozukara** [comment]
> > @FurkanGozukara, the controlnet branch is far from ready, and I don't have an ETA yet. For now I concentrated on getting the existing stuff working well, especially the LoRA part (v0.2.0). ControlNet will be a non backward-compatabile break therefore I want to try to make it flexible enough to not break in the near future again.
> > @FlamingJay can you provide details on how your method works?
> 
> hi, I just upload my implementation at [tensorrt_control_lora](https://github.com/FlamingJay/Stable-Diffusion-WebUI-TensorRT/tree/control_lora). This method is a bit cumbersome. Read the info.md first.

nice work. but regular users wouldnt like. does it break non TensorRT usage?

**Comment by FlamingJay** [comment]
> > > @FurkanGozukara, the controlnet branch is far from ready, and I don't have an ETA yet. For now I concentrated on getting the existing stuff working well, especially the LoRA part (v0.2.0). ControlNet will be a non backward-compatabile break therefore I want to try to make it flexible enough to not break in the near future again.
> > > @FlamingJay can you provide details on how your method works?
> > 
> > 
> > hi, I just upload my implementation at [tensorrt_control_lora](https://github.com/FlamingJay/Stable-Diffusion-WebUI-TensorRT/tree/control_lora). This method is a bit cumbersome. Read the info.md first.
> 
> nice work. but regular users wouldnt like. does it break non TensorRT usage?

It won't. The engine is default to be None.

**Comment by contentis** [comment]
I really like the idea of reusing the existing ControlNet extension and looking through the code; this seems to be a really clean solution. But it comes with its tradeoffs, mainly the lack of control over the extension sources and installation. This is further complicated by its GPL licence, as redistributing it as an artefact in the releases is impacted by the copyleft. 

I will spend some more time with your implementation and see what the best way forward is. If you're (@FlamingJay) interested in contributing, I can reach out to you once I've decided.

As this has become off-topic, are you fine with closing this specific issue?

**Comment by FlamingJay** [comment]
> I really like the idea of reusing the existing ControlNet extension and looking through the code; this seems to be a really clean solution. But it comes with its tradeoffs, mainly the lack of control over the extension sources and installation. This is further complicated by its GPL licence, as redistributing it as an artefact in the releases is impacted by the copyleft.
> 
> I will spend some more time with your implementation and see what the best way forward is. If you're (@FlamingJay) interested in contributing, I can reach out to you once I've decided.
> 
> As this has become off-topic, are you fine with closing this specific issue?

Of course, I'm happy to receive your comments and thank you for your time.
