### ISSUE TITLE
bug: webui 1.7.0 stucks when tensorrt extension is enabled

### ISSUE THREAD

**Issue by bedovyy** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#204]
after updating webui to 1.7.0, running webui is stucked as

```
################################################################
Install script for stable-diffusion + Web UI
Tested on Debian 11 (Bullseye), Fedora 34+ and openSUSE Leap 15.4 or newer.
################################################################

################################################################
Running on bedovyy user
################################################################

################################################################
Repo already cloned, using it as install directory
################################################################

################################################################
python venv already activate or run without venv: /home/bedovyy/Servers/stable-diffusion-webui/venv
################################################################

################################################################
Launching launch.py...
################################################################
Using TCMalloc: libtcmalloc_minimal.so.4
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
Version: v1.7.0
Commit hash: cf2772fab0af5573da775e7437e6acdca424f26e
```

below is stack trace after interrupt (Ctrl + C)
```
^CTraceback (most recent call last):
  File "/home/bedovyy/Servers/stable-diffusion-webui/launch.py", line 48, in <module>
    main()
  File "/home/bedovyy/Servers/stable-diffusion-webui/launch.py", line 39, in main
    prepare_environment()
  File "/home/bedovyy/Servers/stable-diffusion-webui/modules/launch_utils.py", line 428, in prepare_environment
    run_extensions_installers(settings_file=args.ui_settings_file)
  File "/home/bedovyy/Servers/stable-diffusion-webui/modules/launch_utils.py", line 274, in run_extensions_installers
    run_extension_installer(path)
  File "/home/bedovyy/Servers/stable-diffusion-webui/modules/launch_utils.py", line 237, in run_extension_installer
    stdout = run(f'"{python}" "{path_installer}"', errdesc=f"Error running install.py for extension {extension_dir}", custom_env=env).strip()
  File "/home/bedovyy/Servers/stable-diffusion-webui/modules/launch_utils.py", line 104, in run
    result = subprocess.run(**run_kwargs)
  File "/usr/lib/python3.10/subprocess.py", line 505, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib/python3.10/subprocess.py", line 1154, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.10/subprocess.py", line 2021, in _communicate
    ready = selector.select(timeout)
  File "/usr/lib/python3.10/selectors.py", line 416, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt
```

commandline opition
```
./webui.sh --listen --port 8080 --api --allow-code --enable-insecure-extension-access --disable-console-progressbars --theme=dark --data-dir /ai/data/sd --gradio-allowed-path /ai/data/sd --opt-sdp-no-mem-attention
```

I don't know --data-dir option affects to this bug.

I could run webui after one of the following,
- running as `./webui.sh ... --skip-install`
- disable tensorrt extension on settings
- comment `install()` from [`extensions/Stable-Diffusion-WebUI-TensorRT/install.py`](https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/blob/main/install.py#L31)

**Comment by ElmerALucier** [comment]
same thing

**Comment by Ainaemaet** [comment]
Can confirm. Gets stuck on 'installing requirements for tensorflow' step and starts fine after removing TensorRT folder from extensions.

**Comment by ElmerALucier** [comment]
Switch to 1.7.0-RC for a quick fix:
```
git checkout 48fae7c
```

**Comment by flzpfnove** [comment]
you just gotta give it time, it's downloading libraries and looks like it's frozen for 10-15 minutes

**Comment by anarchist912** [comment]
> Switch to 1.7.0-RC for a quick fix:
> 
> ```
> git checkout 48fae7c
> ```

Unfortunately doesn't fix the problem for me. Reverting back to v1.6.1 does however.

**Comment by andrewtvuong** [comment]
Here's the issue https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/issues/225 and the fix https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/pull/226/commits/7c93523628813058732e737aaac84ec3f2c4e48c

Basically if you're stuck:

1. Delete stable-diffusion-webui/venv dir
2. Delete existing (if existing) extensions/Stable-Diffusion-WebUI-TensorRT
3. Rerun webui.sh to rebuild venv
4. source venv/bin/activate in the stable-diffusion-webui dir
5. Then you can either apply my fix https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/commit/7c93523628813058732e737aaac84ec3f2c4e48c to https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/blob/main/install.py and run python install.py or using the A1111 SD UI install my repo instead https://github.com/andrewtvuong/Stable-Diffusion-WebUI-TensorRT

**Comment by bedovyy** [comment]
> Here's the issue #225 and the fix [7c93523](https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/commit/7c93523628813058732e737aaac84ec3f2c4e48c)
> 
> The install script is blocked, so it seems to hang forever.
> 
> Basically if you're stuck:
> 
> 1. Delete stable-diffusion-webui/venv dir
> 2. Delete existing (if existing) extensions/Stable-Diffusion-WebUI-TensorRT
> 3. Rerun webui.sh to rebuild venv
> 4. `source venv/bin/activate` in the stable-diffusion-webui dir **MAKE ABSOLUTELY SURE THIS IS ENABLED**
> 
> 
> ```
> pip uninstall -y tensorrt
> pip install -y nvidia-cudnn-cu11==8.9.4.25 --no-cache-dir
> pip install --pre --extra-index-url https://pypi.nvidia.com tensorrt==9.0.1.post11.dev4 --no-cache-dir
> pip uninstall -y nvidia-cudnn-cu11
> ```
> 
> 6. `deactivate`
> 7. Proceed with normal installation of Nvidia TensorRT
> 
> --- alternative, not recommend unless you know what you're doing
> 
> Then you can either apply my fix [7c93523](https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/commit/7c93523628813058732e737aaac84ec3f2c4e48c) to https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/blob/main/install.py and run `python install.py`
> 
> or using the A1111 SD UI install my repo instead https://github.com/andrewtvuong/Stable-Diffusion-WebUI-TensorRT as a temporary work around. Once the main package is fixed, I would uninstall and install the main again.

Thank you for the good investigation.
I uninstalled nvidia-cudnn-cu11 from my env, then I could run webui properly.

I hope your patch applied fast.

**Comment by bedovyy** [comment]
fixed on dev branch([c73d9cd](https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/commit/c73d9cdf27a01968c56cae500f56f4b5c6224f86))

**Comment by hendersj** [comment]
Just wanted to see if this was in the main branch - I try installing this plugin from within A1111 and I see what this bug references; I'm guessing that installing from within the 'extensions' manager doesn't pull the dev branch, though.

**Comment by Codyport** [comment]
It doesn't look like it's promoted to the main code yet - the linked code above has a banner warning -- 
_This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository._

Checking the install.py in the dev branch, it doesn't include the new content that's linked in that bug either.  So it doesn't seem to be available in either main or dev.

**Comment by Codyport** [comment]
Andrew's [solution](https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/issues/204#issuecomment-1879870974) worked for me in the meantime.
