### ISSUE TITLE
Unable to run HighRes Fix while 

### ISSUE THREAD

**Issue by Shreddertheman** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#22]
It just doesnt run high res when I use this

**Comment by racerx2oo3** [comment]
You need to have engines that can support both the starting image size and the ending image size.  So if you are using 512x512 and using 2x upscaling you'd need an engine that supported 512x512 which is the starting image (this would be covered by the default engine), and you'd need an engine that covers 1024x1024 which is the ending resolution size. (you would need to create either another engine to cover this range.)  The extension will use the default engine to start and then switch to the larger resolution engine when it needs to handle the scale to 1024x1024.

**Comment by contentis** [comment]
Related: #15

**Comment by contentis** [comment]
Closing as this is expected behaviour. Feel free to reopen if you encounter further issues.
