### ISSUE TITLE
Error running install.py / SD version error

### ISSUE THREAD

**Issue by T9es** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#220]
```
*** Error running install.py for extension F:\AI-GIT-CLONE\REPAIR\stable-diffusion-webui\extensions\Stable-Diffusion-WebUI-TensorRT.
*** Command: "F:\AI-GIT-CLONE\REPAIR\stable-diffusion-webui\venv\Scripts\python.exe" "F:\AI-GIT-CLONE\REPAIR\stable-diffusion-webui\extensions\Stable-Diffusion-WebUI-TensorRT\install.py"
*** Error code: 1
*** stdout: removing nvidia-cudnn-cu11
***
*** stderr: Traceback (most recent call last):
***   File "F:\AI-GIT-CLONE\REPAIR\stable-diffusion-webui\extensions\Stable-Diffusion-WebUI-TensorRT\install.py", line 67, in <module>
***     install()
***   File "F:\AI-GIT-CLONE\REPAIR\stable-diffusion-webui\extensions\Stable-Diffusion-WebUI-TensorRT\install.py", line 33, in install
***     launch.run(
***   File "F:\AI-GIT-CLONE\REPAIR\stable-diffusion-webui\modules\launch_utils.py", line 116, in run
***     raise RuntimeError("\n".join(error_bits))
*** RuntimeError: Error running command.
*** Command: ['python', '-m', 'pip', 'uninstall', '-y', 'nvidia-cudnn-cu11']
*** Error code: 9009
```

Seems broken after the new update. Might be caused by my python install, although I re-installed it by now 3 times, including setting correct argument paths in the webui. Every other extension works.

**Comment by SenaKashiwazaki** [comment]
> After applying [the guide](https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/issues/27#issuecomment-1767570566)
> 
> ```
> *** Error executing callback ui_tabs_callback for F:\AI-GIT-CLONE\REPAIR\stable-diffusion-webui\extensions\Stable-Diffusion-WebUI-TensorRT\scripts\trt.py
>     Traceback (most recent call last):
>       File "F:\AI-GIT-CLONE\REPAIR\stable-diffusion-webui\modules\script_callbacks.py", line 166, in ui_tabs_callback
>         res += c.callback() or []
>       File "F:\AI-GIT-CLONE\REPAIR\stable-diffusion-webui\extensions\Stable-Diffusion-WebUI-TensorRT\ui_trt.py", line 612, in on_ui_tabs
>         choices=get_valid_lora_checkpoints(),
>       File "F:\AI-GIT-CLONE\REPAIR\stable-diffusion-webui\extensions\Stable-Diffusion-WebUI-TensorRT\ui_trt.py", line 290, in get_valid_lora_checkpoints
>         available_lora_models = get_lora_checkpoints()
>       File "F:\AI-GIT-CLONE\REPAIR\stable-diffusion-webui\extensions\Stable-Diffusion-WebUI-TensorRT\ui_trt.py", line 271, in get_lora_checkpoints
>         version = SDVersion.from_str(config["sd version"])
>     KeyError: 'sd version'
> ```

I'm having the exact same issue with exactly the same error messages.

**Comment by hkpD** [comment]
Same issue with same error.

**Comment by andrewtvuong** [comment]
check this out https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/issues/225

**Comment by SenaKashiwazaki** [comment]
> check this fix out #225

I tried this fix and its returning a very similar issue for me still.

` Error executing callback ui_tabs_callback for C:\Users\user\stable-diffusion-webui\extensions\Stable-Diffusion-WebUI-TensorRT\scripts\trt.py
    Traceback (most recent call last):
      File "C:\Users\user\stable-diffusion-webui\modules\script_callbacks.py", line 166, in ui_tabs_callback
        res += c.callback() or []
               ^^^^^^^^^^^^
      File "C:\Users\user\stable-diffusion-webui\extensions\Stable-Diffusion-WebUI-TensorRT\ui_trt.py", line 682, in on_ui_tabs
        elem_id=f"trt_profiles_markdown", value=get_trt_profiles_markdown()
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\user\stable-diffusion-webui\extensions\Stable-Diffusion-WebUI-TensorRT\ui_trt.py", line 657, in get_trt_profiles_markdown
        engine_cards, lora_cards = engine_profile_card()
                                   ^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\user\stable-diffusion-webui\extensions\Stable-Diffusion-WebUI-TensorRT\ui_trt.py", line 370, in engine_profile_card
        s_min, s_opt, s_max = m["config"].profile.get(
                              ^^^^^^^^^^^^^^^^^^^^^^^
    AttributeError: 'list' object has no attribute 'get'`

**Comment by hkpD** [comment]
> check this fix out #225

this did not fix the issue for me. i am still receiving "KeyError: 'sd version'" error

**Comment by paolocrosato** [comment]
Check your lora folders, you probably have a .json file for each of your lora safetensors file. The extensions save some information for each Lora on a json file with the same name, which is something every other extension working with lora does, like civitai helper or any scan like that.
Remove every json file from your lora dir and subdir and it will work.

Changing the config file name to something like: loraname-tensort-cfg.json should fix the issue, in ui_trt.py:

`config_file = os.path.join(cmd_opts.lora_dir, name + ".json")`

**Comment by solidst8ip** [comment]
> Check your lora folders, you probably have a .json file for each of your lora safetensors file. The extensions save some information for each Lora on a json file with the same name, which is something every other extension working with lora does, like civitai helper or any scan like that. Remove every json file from your lora dir and subdir and it will work.
> 
> Changing the config file name to something like: loraname-tensort-cfg.json should fix the issue, in ui_trt.py:
> 
> `config_file = os.path.join(cmd_opts.lora_dir, name + ".json")`
> 
> and in every other place it is referenced.

Worked perfectly! As a Python noob, thank you so much!

**Comment by caoddgao** [comment]
bravo, thank you so much. Man, you are the only one to clearly give the solution all over the world. ahhaha, Best luck
