### ISSUE TITLE
AttributeError: 'list' object has no attribute 'get'

### ISSUE THREAD

**Issue by swumagic** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#227]
No config file found for chineseβmalelikeness. You can generate it in the LoRA tab.
No config file found for ClothingAdjuster3. You can generate it in the LoRA tab.
No config file found for sd_xl_offset_example-lora_1.0. You can generate it in the LoRA tab.
No config file found for edgFuturisticXL. You can generate it in the LoRA tab.
No config file found for PrgXL_V1. You can generate it in the LoRA tab.
No config file found for ArienDragonGirlV1-SDXL. You can generate it in the LoRA tab.
*** Error executing callback ui_tabs_callback for J:\StableDiffusion\sdwebui\extensions\Stable-Diffusion-WebUI-TensorRT\scripts\trt.py
    Traceback (most recent call last):
      File "J:\StableDiffusion\sdwebui\modules\script_callbacks.py", line 166, in ui_tabs_callback
        res += c.callback() or []
      File "J:\StableDiffusion\sdwebui\extensions\Stable-Diffusion-WebUI-TensorRT\ui_trt.py", line 682, in on_ui_tabs
        elem_id=f"trt_profiles_markdown", value=get_trt_profiles_markdown()
      File "J:\StableDiffusion\sdwebui\extensions\Stable-Diffusion-WebUI-TensorRT\ui_trt.py", line 657, in get_trt_profiles_markdown
        engine_cards, lora_cards = engine_profile_card()
      File "J:\StableDiffusion\sdwebui\extensions\Stable-Diffusion-WebUI-TensorRT\ui_trt.py", line 370, in engine_profile_card
        s_min, s_opt, s_max = m["config"].profile.get(
    AttributeError: 'list' object has no attribute 'get'

---

**Comment by swumagic** [comment]
Win11，SD1.7.0, PYTHON 3.10.11,rtx4090

**Comment by swumagic** [comment]
cuda11.8+xformers0.0.23.post1+torch2.1.2

**Comment by swumagic** [comment]
https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/commit/4c2bcafd854f7bc74d3ca9c5c3c90112e9fe6e55  
I returned to this earlier version and it ran normally, but the version on January 5, 2024 did not run. The above error occurred, indicating that there is indeed a problem with the updated version.

**Comment by ItsSkynet** [comment]
> [4c2bcaf](https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/commit/4c2bcafd854f7bc74d3ca9c5c3c90112e9fe6e55) I returned to this earlier version and it ran normally, but the version on January 5, 2024 did not run. The above error occurred, indicating that there is indeed a problem with the updated version.

im having the same issues as well, i append the error callback response here:
`*** Error executing callback ui_tabs_callback for Y:\StableDiffusion\stabilityMatrix\Packages\Stable Diffusion WebUI\extensions\Stable-Diffusion-WebUI-TensorRT\scripts\trt.py
    Traceback (most recent call last):
      File "Y:\StableDiffusion\stabilityMatrix\Packages\Stable Diffusion WebUI\modules\script_callbacks.py", line 166, in ui_tabs_callback
        res += c.callback() or []
      File "Y:\StableDiffusion\stabilityMatrix\Packages\Stable Diffusion WebUI\extensions\Stable-Diffusion-WebUI-TensorRT\ui_trt.py", line 682, in on_ui_tabs
        elem_id=f"trt_profiles_markdown", value=get_trt_profiles_markdown()
      File "Y:\StableDiffusion\stabilityMatrix\Packages\Stable Diffusion WebUI\extensions\Stable-Diffusion-WebUI-TensorRT\ui_trt.py", line 657, in get_trt_profiles_markdown
        engine_cards, lora_cards = engine_profile_card()
      File "Y:\StableDiffusion\stabilityMatrix\Packages\Stable Diffusion WebUI\extensions\Stable-Diffusion-WebUI-TensorRT\ui_trt.py", line 370, in engine_profile_card
        s_min, s_opt, s_max = m["config"].profile.get(
    AttributeError: 'list' object has no attribute 'get'

---`

i have reinstalled manually using this tutorial as well and same issues happen: [https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/issues/27#issuecomment-1767570566](https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/issues/27#issuecomment-1767570566)

**Comment by ItsSkynet** [comment]
I have figured it out.

Delete your Unet-onnx and Unet-trt folders... that fixed the issue. i have backed up all the files and i will restore them after running the new set of instructions inside the Tensor RT tab. Will post findings afterwards.

**Comment by ItsSkynet** [comment]
ok, i successfully migrated my backup of the dev branch models into the stable 0.2.0 version.
Changes have been made to the models.json file inside "Unet-trt", it no longer has the lora information inside of it, instead it opts for reading all ".lora" files inside the directory. i assume that the old ".trt" files for the lora engines just got an extension rename into ".lora", so they might just need an extension rename.

So to properly fix this issue, one needs to edit the old models.json file to remove all lora keys/data from it. afterwards it will load fine, but have its lora missing, for that just renaming the extension of all loras from trt to .lora should fix it.

**Comment by swumagic** [comment]
*** Error loading script: trt.py
    Traceback (most recent call last):
      File "J:\StableDiffusion\sdwebui\modules\scripts.py", line 469, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "J:\StableDiffusion\sdwebui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "J:\StableDiffusion\sdwebui\extensions\Stable-Diffusion-WebUI-TensorRT\scripts\trt.py", line 13, in <module>
        import ui_trt
      File "J:\StableDiffusion\sdwebui\extensions\Stable-Diffusion-WebUI-TensorRT\ui_trt.py", line 19, in <module>
        from model_manager import modelmanager, cc_major, TRT_MODEL_DIR
      File "J:\StableDiffusion\sdwebui\extensions\Stable-Diffusion-WebUI-TensorRT\model_manager.py", line 237, in <module>
        modelmanager = ModelManager()
      File "J:\StableDiffusion\sdwebui\extensions\Stable-Diffusion-WebUI-TensorRT\model_manager.py", line 41, in __init__
        self.all_models = self.read_json()
      File "J:\StableDiffusion\sdwebui\extensions\Stable-Diffusion-WebUI-TensorRT\model_manager.py", line 161, in read_json
        out = json.load(f)
      File "json\__init__.py", line 293, in load
      File "json\__init__.py", line 346, in loads
      File "json\decoder.py", line 337, in decode
      File "json\decoder.py", line 353, in raw_decode
    json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 195 column 5 (char 6676)

---

**Comment by swumagic** [comment]
No config file found for MechaGirl_v1. You can generate it in the LoRA tab.
No config file found for ruirui2700. You can generate it in the LoRA tab.
No config file found for chineseβmalelikeness3. You can generate it in the LoRA tab.
No config file found for chineseβmalelikeness. You can generate it in the LoRA tab.
No config file found for ClothingAdjuster3. You can generate it in the LoRA tab.
No config file found for sd_xl_offset_example-lora_1.0. You can generate it in the LoRA tab.
No config file found for edgFuturisticXL. You can generate it in the LoRA tab.
No config file found for PrgXL_V1. You can generate it in the LoRA tab.
No config file found for ArienDragonGirlV1-SDXL. You can generate it in the LoRA tab.

**Comment by swumagic** [comment]
Thanks. After deleting the Lora configuration data in json, you can run the latest 0.2.0 extension, but there is still a  reminder to detect all lora files in the original model folder and convert them into trt.

> No config file found for MechaGirl_v1. You can generate it in the LoRA tab.找不到 MechaGirl_v1 的配置文件。您可以在 LoRA 选项卡中生成它。 No config file found for ruirui2700. You can generate it in the LoRA tab.未找到 ruirui2700 的配置文件。您可以在 LoRA 选项卡中生成它。 No config file found for chineseβmalelikeness3. You can generate it in the LoRA tab. 找不到 chineseβmalelikeness3 的配置文件。您可以在 LoRA 选项卡中生成它。 No config file found for chineseβmalelikeness. You can generate it in the LoRA tab. 未找到 chineseβmalelikeness 的配置文件。您可以在 LoRA 选项卡中生成它。 No config file found for ClothingAdjuster3. You can generate it in the LoRA tab. 找不到 ClothingAdjuster3 的配置文件。您可以在 LoRA 选项卡中生成它。 No config file found for sd_xl_offset_example-lora_1.0. You can generate it in the LoRA tab. 找不到 sd_xl_offset_example-lora_1.0 的配置文件。您可以在 LoRA 选项卡中生成它。 No config file found for edgFuturisticXL. You can generate it in the LoRA tab. 找不到 edgFuturisticXL 的配置文件。您可以在 LoRA 选项卡中生成它。 No config file found for PrgXL_V1. You can generate it in the LoRA tab. 找不到 PrgXL_V1 的配置文件。您可以在 LoRA 选项卡中生成它。 No config file found for ArienDragonGirlV1-SDXL. You can generate it in the LoRA tab. 未找到 ArienDragonGirlV1-SDXL 的配置文件。您可以在 LoRA 选项卡中生成它。

**Comment by ItsSkynet** [comment]
> Thanks. After deleting the Lora configuration data in json, you can run the latest 0.2.0 extension, but there is still a reminder to detect all lora files in the original model folder and convert them into trt.
> 
> > No config file found for MechaGirl_v1. You can generate it in the LoRA tab.找不到 MechaGirl_v1 的配置文件。您可以在 LoRA 选项卡中生成它。 No config file found for ruirui2700. You can generate it in the LoRA tab.未找到 ruirui2700 的配置文件。您可以在 LoRA 选项卡中生成它。 No config file found for chineseβmalelikeness3. You can generate it in the LoRA tab. 找不到 chineseβmalelikeness3 的配置文件。您可以在 LoRA 选项卡中生成它。 No config file found for chineseβmalelikeness. You can generate it in the LoRA tab. 未找到 chineseβmalelikeness 的配置文件。您可以在 LoRA 选项卡中生成它。 No config file found for ClothingAdjuster3. You can generate it in the LoRA tab. 找不到 ClothingAdjuster3 的配置文件。您可以在 LoRA 选项卡中生成它。 No config file found for sd_xl_offset_example-lora_1.0. You can generate it in the LoRA tab. 找不到 sd_xl_offset_example-lora_1.0 的配置文件。您可以在 LoRA 选项卡中生成它。 No config file found for edgFuturisticXL. You can generate it in the LoRA tab. 找不到 edgFuturisticXL 的配置文件。您可以在 LoRA 选项卡中生成它。 No config file found for PrgXL_V1. You can generate it in the LoRA tab. 找不到 PrgXL_V1 的配置文件。您可以在 LoRA 选项卡中生成它。 No config file found for ArienDragonGirlV1-SDXL. You can generate it in the LoRA tab. 未找到 ArienDragonGirlV1-SDXL 的配置文件。您可以在 LoRA 选项卡中生成它。

that is because the lora file name has to match with the list it gave you in the traceback log.

Example: MechaGirl_v1 has to be named "MechaGirl_v1.lora", its case-sensitive.
