### ISSUE TITLE
Install failed part-way and now thinks it's installed, but doesn't work and can't uninstall

### ISSUE THREAD

**Issue by pdavis68** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#228]
I tried to install the TensorRT extension in Windows, but apparently you need to be running as admin for it to install. It failed part-way with a permission issue.
But now it thinks it's installed and I can't figure out how to uninstall it so that I can rerun the install as admin.

I get errors like:

** Error running process_batch: D:\stable-diffusion-webui\extensions\Stable-Diffusion-WebUI-TensorRT\scripts\trt.pyt/s]
    Traceback (most recent call last):
      File "D:\stable-diffusion-webui\modules\scripts.py", line 742, in process_batch
        script.process_batch(p, *script_args, **kwargs)
      File "D:\stable-diffusion-webui\extensions\Stable-Diffusion-WebUI-TensorRT\scripts\trt.py", line 302, in process_batch
        if self.idx != sd_unet.current_unet.profile_idx:
    AttributeError: 'NoneType' object has no attribute 'profile_idx'

**Comment by ItsSkynet** [comment]
you need to delete your VENV folder as well as the extension, then re-generate the VENV trough webui.bat or by running the instance of StabilityMatrix, then you can re-install the extension afterwards. (check: [https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/issues/27#issuecomment-1767570566](https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/issues/27#issuecomment-1767570566) )

Note that the new version 0.2.0 came with changes that were not anticipated and broke a lot of stuff from before. a couple of things need to be done to some files inside models/unet-trt/models.json

1. edit the old models.json file to remove all lora keys/data from it.
2. edit all lora files with the ".trt" extension to have it changed to ".lora" (dev branch generated).
3. force rebuild all your Tensor RT Checkpoint profiles (the way it was before).

**Comment by pdavis68** [comment]
@ItsSkynet 
Thank you for the reply. Currently reinstalling the extension...

- edit the old models.json file to remove all lora keys/data from it.
Where would I find this file? I can't find it anywhere in my stable-diffusion-webui folder or its subfolders?

- edit all lora files with the ".trt" extension to have it changed to ".lora" (dev branch generated).
I don't have any of these. Should I?

- force rebuild all your Tensor RT Checkpoint profiles (the way it was before).
I've never used it before. This was my first time installing it. 
-

**Comment by ItsSkynet** [comment]
> @ItsSkynet Thank you for the reply. Currently reinstalling the extension...
> 
> * edit the old models.json file to remove all lora keys/data from it.
>   Where would I find this file? I can't find it anywhere in my stable-diffusion-webui folder or its subfolders?
> * edit all lora files with the ".trt" extension to have it changed to ".lora" (dev branch generated).
>   I don't have any of these. Should I?
> * force rebuild all your Tensor RT Checkpoint profiles (the way it was before).
>   I've never used it before. This was my first time installing it.

First time install and it failed? then you dont need to rebuild the models.json since you dont have any profiles generated in the past. just focus on #27

**Comment by pdavis68** [comment]
Thanks @ItsSkynet . Got it installed after another hiccup. Had to update pip, delete the extension again, and THEN it worked.

Thanks for the help!
