### ISSUE TITLE
sd_unet dropdown menu  is empty,but i gen 3 models

### ISSUE THREAD

**Issue by gdtiti** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#23]
sd_unet dropdown menu  is empty,but i gen 3 models in Unet-onnx

**Comment by OmegaDraquex** [comment]
I had the same issue. It seems like the Exporter kept failing to fully develop the Unet until I disabled --api and reran the Exporter.

**Comment by contentis** [comment]
Related / Same issue: #17

**Comment by contentis** [comment]
I've documented that `--api` can cause issues when exporting in the readme now. I'll close as this seems to be resolved. Feel free to reopen if you still encounter issues.
