### ISSUE TITLE
PermissionError: [Errno 13] - model.json denied

### ISSUE THREAD

**Issue by iKurama** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#234]
Hiya!

So, I haven't seen this particular issue anywhere in open or closed issues, nor can I find the model.json file anywhere in my folders are on here, hence I've lucked out.

With help from #27, I've gotten rid of the popups from #186, but the issue still persists.

> 
venv "E:\SDXL\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.7.0
Commit hash: cf2772fab0af5573da775e7437e6acdca424f26e
removing nvidia-cudnn-cu11
Successfully uninstalled nvidia-cudnn-cu11
Launching Web UI with arguments: --no-half-vae --xformers
WARNING:root:Model file does not exist. Creating new one.
*** Error loading script: trt.py
    Traceback (most recent call last):
      File "E:\SDXL\modules\scripts.py", line 469, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\SDXL\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\SDXL\extensions\Stable-Diffusion-WebUI-TensorRT\scripts\trt.py", line 13, in <module>
        import ui_trt
      File "E:\SDXL\extensions\Stable-Diffusion-WebUI-TensorRT\ui_trt.py", line 19, in <module>
        from model_manager import modelmanager, cc_major, TRT_MODEL_DIR
      File "E:\SDXL\extensions\Stable-Diffusion-WebUI-TensorRT\model_manager.py", line 237, in <module>
        modelmanager = ModelManager()
      File "E:\SDXL\extensions\Stable-Diffusion-WebUI-TensorRT\model_manager.py", line 43, in __init__
        self.update()
      File "E:\SDXL\extensions\Stable-Diffusion-WebUI-TensorRT\model_manager.py", line 98, in update
        self.write_json()
      File "E:\SDXL\extensions\Stable-Diffusion-WebUI-TensorRT\model_manager.py", line 156, in write_json
        with open(self.model_file, "w") as f:
    PermissionError: [Errno 13] Permission denied: 'E:\\SDXL\\models\\Unet-trt\\model.json'

---
Exception ignored in: <function ModelManager.__del__ at 0x000001B16E7FC430>
Traceback (most recent call last):
  File "E:\SDXL\extensions\Stable-Diffusion-WebUI-TensorRT\model_manager.py", line 101, in __del__
    self.update()
  File "E:\SDXL\extensions\Stable-Diffusion-WebUI-TensorRT\model_manager.py", line 98, in update
    self.write_json()
  File "E:\SDXL\extensions\Stable-Diffusion-WebUI-TensorRT\model_manager.py", line 156, in write_json
    with open(self.model_file, "w") as f:
PermissionError: [Errno 13] Permission denied: 'E:\\SDXL\\models\\Unet-trt\\model.json'
ControlNet preprocessor location: E:\SDXL\extensions\sd-webui-controlnet\annotator\downloads
2024-01-09 20:09:56,192 - ControlNet - INFO - ControlNet v1.1.427
2024-01-09 20:09:56,315 - ControlNet - INFO - ControlNet v1.1.427
Loading weights [4777906d2d] from E:\SDXL\models\Stable-diffusion\SDXL\animexlXuebimix_v60LCM.safetensors
2024-01-09 20:09:56,807 - AnimateDiff - INFO - Injecting LCM to UI.
2024-01-09 20:09:57,101 - AnimateDiff - INFO - Hacking i2i-batch.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Creating model from config: E:\SDXL\repositories\generative-models\configs\inference\sd_xl_base.yaml
Startup time: 23.6s (prepare environment: 9.9s, import torch: 3.8s, import gradio: 1.3s, setup paths: 1.0s, initialize shared: 0.3s, other imports: 0.8s, setup codeformer: 0.3s, load scripts: 3.6s, create ui: 1.0s, gradio launch: 1.3s).
Loading VAE weights specified in settings: E:\SDXL\models\VAE\sdxl_vae.safetensors
Applying attention optimization: xformers... done.
Model loaded in 14.2s (load weights from disk: 2.0s, create model: 0.9s, apply weights to model: 9.4s, apply half(): 0.1s, apply dtype to VAE: 0.2s, load VAE: 0.7s, move model to device: 0.1s, calculate empty prompt: 0.7s).

**Comment by ItsSkynet** [comment]
> Hiya!
> 
> So, I haven't seen this particular issue anywhere in open or closed issues, nor can I find the model.json file anywhere in my folders are on here, hence I've lucked out.
> 
> With help from #27, I've gotten rid of the popups from #186, but the issue still persists.
> 
> > 
> 
> venv "E:\SDXL\venv\Scripts\Python.exe" Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug 1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)] Version: v1.7.0 Commit hash: cf2772fab0af5573da775e7437e6acdca424f26e removing nvidia-cudnn-cu11 Successfully uninstalled nvidia-cudnn-cu11 Launching Web UI with arguments: --no-half-vae --xformers WARNING:root:Model file does not exist. Creating new one. *** Error loading script: trt.py Traceback (most recent call last): File "E:\SDXL\modules\scripts.py", line 469, in load_scripts script_module = script_loading.load_module(scriptfile.path) File "E:\SDXL\modules\script_loading.py", line 10, in load_module module_spec.loader.exec_module(module) File "", line 883, in exec_module File "", line 241, in _call_with_frames_removed File "E:\SDXL\extensions\Stable-Diffusion-WebUI-TensorRT\scripts\trt.py", line 13, in import ui_trt File "E:\SDXL\extensions\Stable-Diffusion-WebUI-TensorRT\ui_trt.py", line 19, in from model_manager import modelmanager, cc_major, TRT_MODEL_DIR File "E:\SDXL\extensions\Stable-Diffusion-WebUI-TensorRT\model_manager.py", line 237, in modelmanager = ModelManager() File "E:\SDXL\extensions\Stable-Diffusion-WebUI-TensorRT\model_manager.py", line 43, in **init** self.update() File "E:\SDXL\extensions\Stable-Diffusion-WebUI-TensorRT\model_manager.py", line 98, in update self.write_json() File "E:\SDXL\extensions\Stable-Diffusion-WebUI-TensorRT\model_manager.py", line 156, in write_json with open(self.model_file, "w") as f: PermissionError: [Errno 13] Permission denied: 'E:\SDXL\models\Unet-trt\model.json'
> 
> Exception ignored in: <function ModelManager.**del** at 0x000001B16E7FC430> Traceback (most recent call last): File "E:\SDXL\extensions\Stable-Diffusion-WebUI-TensorRT\model_manager.py", line 101, in **del** self.update() File "E:\SDXL\extensions\Stable-Diffusion-WebUI-TensorRT\model_manager.py", line 98, in update self.write_json() File "E:\SDXL\extensions\Stable-Diffusion-WebUI-TensorRT\model_manager.py", line 156, in write_json with open(self.model_file, "w") as f: PermissionError: [Errno 13] Permission denied: 'E:\SDXL\models\Unet-trt\model.json' ControlNet preprocessor location: E:\SDXL\extensions\sd-webui-controlnet\annotator\downloads 2024-01-09 20:09:56,192 - ControlNet - INFO - ControlNet v1.1.427 2024-01-09 20:09:56,315 - ControlNet - INFO - ControlNet v1.1.427 Loading weights [4777906d2d] from E:\SDXL\models\Stable-diffusion\SDXL\animexlXuebimix_v60LCM.safetensors 2024-01-09 20:09:56,807 - AnimateDiff - INFO - Injecting LCM to UI. 2024-01-09 20:09:57,101 - AnimateDiff - INFO - Hacking i2i-batch. Running on local URL: http://127.0.0.1:7860
> 
> To create a public link, set `share=True` in `launch()`. Creating model from config: E:\SDXL\repositories\generative-models\configs\inference\sd_xl_base.yaml Startup time: 23.6s (prepare environment: 9.9s, import torch: 3.8s, import gradio: 1.3s, setup paths: 1.0s, initialize shared: 0.3s, other imports: 0.8s, setup codeformer: 0.3s, load scripts: 3.6s, create ui: 1.0s, gradio launch: 1.3s). Loading VAE weights specified in settings: E:\SDXL\models\VAE\sdxl_vae.safetensors Applying attention optimization: xformers... done. Model loaded in 14.2s (load weights from disk: 2.0s, create model: 0.9s, apply weights to model: 9.4s, apply half(): 0.1s, apply dtype to VAE: 0.2s, load VAE: 0.7s, move model to device: 0.1s, calculate empty prompt: 0.7s).

models.json is located in: models/unet-trt/models.json

**Comment by iKurama** [comment]
-snip-
    PermissionError: [Errno 13] Permission denied: 'E:\\SDXL\\models\\Unet-trt\\model.json'

---
Exception ignored in: <function ModelManager.__del__ at 0x0000026AA4460430>
Traceback (most recent call last):
  File "E:\SDXL\extensions\Stable-Diffusion-WebUI-TensorRT\model_manager.py", line 101, in __del__
    self.update()
  File "E:\SDXL\extensions\Stable-Diffusion-WebUI-TensorRT\model_manager.py", line 98, in update
    self.write_json()
  File "E:\SDXL\extensions\Stable-Diffusion-WebUI-TensorRT\model_manager.py", line 156, in write_json
    with open(self.model_file, "w") as f:


//////////
That's a fresh install from the dev branch, while it has the empty model.json file in it.

**Comment by ItsSkynet** [comment]
for the looks of things, it looks like write permissions for the folder/file are disabled, have you tried starting it with elevated permissions? (open as administrator) or maybe the folder is set as read only.

**Comment by iKurama** [comment]
All the folders have full control/permission though :/

**Comment by ItsSkynet** [comment]
> All the folders have full control/permission though :/

that is weird, try installing a separate instance with a package manager like StabilityMatrix and see if that fixes the issue. something is wrong with either the account permissions, drive permissions or the stable diffusion installation is broken.

**Comment by iKurama** [comment]
It successfully installed, but webui halts with loading. with TRT installed

**Comment by iKurama** [comment]
Probably just gonna wait till I reset the pc, but thanks for the help

**Comment by iKurama** [comment]
This might be a dummy mistake on my end /windows' end.
I had to go into advanced settings and SIGN IN, with my OLD PASSWORD ...
Thanks windows, you're useless.
