### ISSUE TITLE
Enabling PyTorch fallback as no engine was found.

### ISSUE THREAD

**Issue by ozymoz** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#236]
I installed TensorRT without getting any error. This error appears when I generate it. I can't use TensorRT optimization. Does anyone have any idea about the problem?

version: [v1.7.0] python: 3.10.11  •  torch: 2.0.1+cu118  •  xformers: 0.0.20  •  gradio: 3.41.2  •  checkpoint: [364cecf630]

![1](https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/assets/41089719/10bcc312-aee0-4b2a-ad3d-d18bc3d90945)
![2](https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/assets/41089719/aae62059-d2ae-48d4-b173-81e2460906c4)

**Comment by Kaiten10** [comment]
I'm having the same issue, did you manage to get it fixed?

**Comment by ozymoz** [comment]
> I'm having the same issue, did you manage to get it fixed?

I did TensorRT model training again. Keep prompt 75 while training. You can change the resolutions.

**Comment by Cosmos-13** [comment]
I have the same problem and I don't understand what you means with "Keep prompt 75 while training."

**Comment by ozymoz** [comment]
> I have the same problem and I don't understand what you mean with "Keep prompt 75 while training.".

Can you train TensorRT as in the image?

![1](https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/assets/41089719/89198381-48f5-48f7-8054-8b66a9e253ab)

**Comment by Cosmos-13** [comment]
Well, once trained, when I try to generate an image, I get another error in the console (and the generation won't start).
My model is DreamShaperXL.
I'm not sure if my error is relevant here after all... 
Anyway, for the moment I haven't had 'Enabling PyTorch fallback as no engine was found." error (well, I haven't been able to verify it).

`txt2img: A boy at the beach,
*** Error running process_batch: G:\IA\sd.webui\webui\extensions\Stable-Diffusion-WebUI-TensorRT\scripts\trt.py
    Traceback (most recent call last):
      File "G:\IA\sd.webui\webui\modules\scripts.py", line 742, in process_batch
        script.process_batch(p, *script_args, **kwargs)
      File "G:\IA\sd.webui\webui\extensions\Stable-Diffusion-WebUI-TensorRT\scripts\trt.py", line 302, in process_batch
        if self.idx != sd_unet.current_unet.profile_idx:
    AttributeError: 'NoneType' object has no attribute 'profile_idx'

---`

**Comment by zmnv** [comment]
The same issue 

![image](https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/assets/25253501/e4034594-2894-4a75-9d8a-9dddb03a1a78)

**Comment by droide** [comment]
try to export again the model
