### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'profile_idx'（change the TensorRT model to another model that is not TensorRT）

### ISSUE THREAD

**Issue by swumagic** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#250]
If you change the TensorRT model to another model that is not TensorRT, the error message with the title above will appear, but the image will still be generated normally.

Loading model 3Guofeng3_v33.safetensors [4078eb4174] (2 out of 2)
Loading weights [4078eb4174] from J:\StableDiffusion\sdwebui\models\Stable-diffusion\3Guofeng3_v33.safetensors
Creating model from config: J:\StableDiffusion\sdwebui\configs\v1-inference.yaml
Applying attention optimization: xformers... done.
Model loaded in 11.6s (load weights from disk: 0.4s, create model: 0.9s, apply weights to model: 10.1s).

*** Error running process_batch: J:\StableDiffusion\sdwebui\extensions\Stable-Diffusion-WebUI-TensorRT\scripts\trt.py
    Traceback (most recent call last):
      File "J:\StableDiffusion\sdwebui\modules\scripts.py", line 742, in process_batch
        script.process_batch(p, *script_args, **kwargs)
      File "J:\StableDiffusion\sdwebui\extensions\Stable-Diffusion-WebUI-TensorRT\scripts\trt.py", line 302, in process_batch
        if self.idx != sd_unet.current_unet.profile_idx:
    AttributeError: 'NoneType' object has no attribute 'profile_idx'

**Comment by LarsiboyCGN** [comment]
Try to edit the file sd.webui\webui\extensions\Stable-Diffusion-WebUI-TensorRT\scripts\trt.py at line 299. 
Change from:
`if self.torch_unet:`
into:
`if self.torch_unet or not sd_unet.current_unet:`

**Comment by swumagic** [comment]
tk

**Comment by bigmover** [comment]
> sd_unet.current_unet is not None and

The extension is available on linux?  Or  what it need  to run except the trt engine? where to place the engine? Any reply will be greatly appreciated.

**Comment by bigmover** [comment]
> Try to edit the file sd.webui\webui\extensions\Stable-Diffusion-WebUI-TensorRT\scripts\trt.py at line 299 Change from: `if self.torch_unet:` into: `if self.torch_unet or not sd_unet.current_unet:`
> 
> And on line 302 from: `if self.idx != sd_unet.current_unet.profile_idx:` into: `if sd_unet.current_unet is not None and self.idx != sd_unet.current_unet.profile_idx:`
> 
> And don't forget to create a profile in TensorRT.
The extension is available on linux? Or what it need to run except the trt engine? where to place the engine? Any reply will be greatly appreciated.

**Comment by LarsiboyCGN** [comment]
> > Try to edit the file sd.webui\webui\extensions\Stable-Diffusion-WebUI-TensorRT\scripts\trt.py at line 299 Change from: `if self.torch_unet:` into: `if self.torch_unet or not sd_unet.current_unet:`
> > And on line 302 from: `if self.idx != sd_unet.current_unet.profile_idx:` into: `if sd_unet.current_unet is not None and self.idx != sd_unet.current_unet.profile_idx:`
> > And don't forget to create a profile in TensorRT.
> 
> The extension is available on linux? Or what it need to run except the trt engine? where to place the engine? Any reply will be greatly appreciated.

The code change only affects the Stable-Diffusion WebUI TensorRT extension, which triggers the mentioned error message in Stable Diffusion. The extension integrates TensorRT with Stable Diffusion and requires profiling before it can be used.

**Comment by fireattack** [comment]
Someone probably can make a PR to incorporate the fix. (But not sure how likely they're going to merge these non-critical changes.)

**Comment by BronxBob** [comment]
> Try to edit the file sd.webui\webui\extensions\Stable-Diffusion-WebUI-TensorRT\scripts\trt.py at line 299 Change from: `if self.torch_unet:` into: `if self.torch_unet or not sd_unet.current_unet:`
> 
> And on line 302 from: `if self.idx != sd_unet.current_unet.profile_idx:` into: `if sd_unet.current_unet is not None and self.idx != sd_unet.current_unet.profile_idx:`
> 
> And don't forget to create a profile in TensorRT.

how do I create a profile in TensorRT?

**Comment by LarsiboyCGN** [comment]
> create a profile in TensorRT

In the Extension there is a Button named "Generate default Engines" ..
[watch on youtube](https://youtu.be/ssPhVOgd1Qc?si=6POjgkCkoKWY_2hN&t=927)

**Comment by BronxBob** [comment]
Don't have that button. Going to uninstall TensorRT and reinstall it to see
if it pops up. Thanks.
