### ISSUE TITLE
Deleting engine profiles?

### ISSUE THREAD

**Issue by Jonseed** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#26]
What is the recommended way to delete engine profiles after they are created, since it seems you can't do it from the UI. Should you just delete the trt and onnx files in models/Unet-trt and models/Unet-onnx? What about the profiles in the model.json file?

**Comment by contentis** [comment]
You can simply delete the model from the Unet-trt folder. The onnx is only being used during export and won't be required from there on but can be beneficial on subsequent exports.

**Comment by rlayfield** [comment]
I don't think that's correct. You also need to modify the models.json. I wasn't able to get the UI to detect their removal until after I manually edited the file myself.

**Comment by algarci104** [comment]
> I don't think that's correct. You also need to modify the models.json. I wasn't able to get the UI to detect their removal until after I manually edited the file myself.

What did you edit within the file to make the UI detect their removal?

**Comment by contentis** [comment]
I pushed some fixed to the main that should better handle updates in the model.json. Generally you need to relaunch webui for these changes to be propagated to the model.json

**Comment by banshek7** [comment]
i too was having this problem when i deleted the model, even after reloading it was showing it was there, then id have to run a search and delete some other thing, but that would remove the extension showing up completely, so id have to redo it all. 

Now im exporting other models and loras and shit so im freaking out and came here to figure out how in the future i can remove them lol. Good to know if it still doesnt work with the DEV version, i can hunt out this models.json or w/e i guess?
