### ISSUE TITLE
Absurdly high memory usage when exporting to ONNX? (V0.2.0)

### ISSUE THREAD

**Issue by T9es** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#264]
I've noticed a HUGE spike in memory usage when exporting a new model in `V0.2.0`. The usage goes from 6gb vram, all the way up to the full 24gb of my 3090, and then it overflows to ram with 14-16gb. 

The overflow to ram might also cause the `Exporting to ONNX failed`, although someone would need to approve this. 

Some additional info: The export was done using static shapes, 
```
batch size 4, 
512 width, 768 height, 
token count 75. 
```

Was trying to investigate another issue with the token count, but this locked me out.

Driver version: `551.23`

This can't be right.

**Comment by Feksaaargh** [comment]
I think this might've been a pytorch issue (namely https://github.com/pytorch/pytorch/commit/b4a49124c8165a374a3ef49e14807ac05b3fc030) but I don't have the know-how to confirm it. Regardless, updating to the 1.8.0 release candidate of the webui (which uses a newer version of pytorch) seems to have fixed it for me and it now peaks around 11GB vram usage when converting an SDXL model.
When recreating the venv for 1.8.0, I had to run `pip install importlib-metadata` in the venv and also follow https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/issues/204#issuecomment-1879870974.

GPU: RTX 4060ti 16GB
Driver: 545.29.06
OS: Linux Mint 21.3 (kernel 6.5.0-18 generic)
Webui commit: eaf5e02

**Comment by MyPod** [comment]
unless I'm misunderstanding, [pytorch/pytorch@b4a4912](https://github.com/pytorch/pytorch/commit/b4a49124c8165a374a3ef49e14807ac05b3fc030) seems to be included as far back as pytorch v2.1.0rc1, so I doubt this is the cause.

**Comment by MyPod** [comment]
FWIW, I'm not saying this is not a problem, just that's unlikely to be the cause of it. I've noted that XL models seem to not undergo the same issue as vram usage/ram spillover is much more contained.

**Comment by T9es** [comment]
I closed it as it's no longer an issue for me. Updated all software aspects, updated the tensorRT itself. Made manual changes in the code too, but that was over half a year ago, can't recall what was changed. 

Seems like reinstalling the extension fixes it most of the time. The only time I've seen some sort of increased VRAM usage is when I **FIRST** generated something without any trt model, then switched to a trt model.

**Comment by iftikharmehdi-metex** [comment]
I found a solution, First generate trt using the first present 256x256 - 512x512 | Batch Size 1-4. Then generate using other presets.

Without generating from the first preset it gives polygraphy.exception.exception.PolygraphyException: Failed to parse ONNX model. Does the model file exist and contain a valid ONNX model?

Strange, but worked for me
