### ISSUE TITLE
Failed to parse ONNX model. Does the model file exist and contain a valid ONNX model?

### ISSUE THREAD

**Issue by silverace71** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#270]
the error is as follows
```
Disabling attention optimization
Exporting mix18.fp16 to TensorRT using - Batch Size: 1-1-4
Height: 512-512-768
Width: 512-512-768
Token Count: 75-75-150
{'sample': [(1, 4, 64, 64), (2, 4, 64, 64), (8, 4, 96, 96)], 'timesteps': [(1,), (2,), (8,)], 'encoder_hidden_states': [(1, 77, 768), (2, 77, 768), (8, 154, 768)]}
============= Diagnostic Run torch.onnx.export version 2.0.1+cu118 =============
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

ERROR:root:Exporting to ONNX failed. Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument mat1 in method wrapper_CUDA_addmm)
============= Diagnostic Run torch.onnx.export version 2.0.1+cu118 =============
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

ERROR:root:Exporting to ONNX failed. Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument weight in method wrapper_CUDA__native_group_norm)
Building TensorRT engine... This can take a while, please check the progress in the terminal.
Building TensorRT engine for A:\AI\Packages\A1111\models\Unet-onnx\mix18.fp16.onnx\encoder.onnx: A:\AI\Packages\A1111\models\Unet-trt\cc86\unet\mix18.fp16\id11a1472e3471eb1aa75d8acec6ea290\encoder.trt
Could not open file A:\AI\Packages\A1111\models\Unet-onnx\mix18.fp16.onnx\encoder.onnx
[E] ModelImporter.cpp:773: Failed to parse ONNX model from file: A:\AI\Packages\A1111\models\Unet-onnx\mix18.fp16.onnx\encoder.onnx
Could not open file A:\AI\Packages\A1111\models\Unet-onnx\mix18.fp16.onnx\encoder.onnx
[!] Failed to parse ONNX model. Does the model file exist and contain a valid ONNX model?
Traceback (most recent call last):
  File "A:\AI\Packages\A1111\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "A:\AI\Packages\A1111\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "A:\AI\Packages\A1111\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "A:\AI\Packages\A1111\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "A:\AI\Packages\A1111\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "A:\AI\Packages\A1111\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "A:\AI\Packages\A1111\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "A:\AI\Packages\A1111\extensions\Stable-Diffusion-WebUI-TensorRT\ui_trt.py", line 249, in export_unet_to_trt
    ret = export_trt(
  File "A:\AI\Packages\A1111\extensions\Stable-Diffusion-WebUI-TensorRT\exporter.py", line 234, in export_trt
    ret = engine.build(
  File "A:\AI\Packages\A1111\extensions\Stable-Diffusion-WebUI-TensorRT\utilities.py", line 251, in build
    network = network_from_onnx_path(
  File "<string>", line 3, in network_from_onnx_path
  File "A:\AI\Packages\A1111\venv\lib\site-packages\polygraphy\backend\base\loader.py", line 40, in __call__
    return self.call_impl(*args, **kwargs)
  File "A:\AI\Packages\A1111\venv\lib\site-packages\polygraphy\util\util.py", line 710, in wrapped
    return func(*args, **kwargs)
  File "A:\AI\Packages\A1111\venv\lib\site-packages\polygraphy\backend\trt\loader.py", line 227, in call_impl
    trt_util.check_onnx_parser_errors(parser, success)
  File "A:\AI\Packages\A1111\venv\lib\site-packages\polygraphy\backend\trt\util.py", line 86, in check_onnx_parser_errors
    G_LOGGER.critical("Failed to parse ONNX model. Does the model file exist and contain a valid ONNX model?")
  File "A:\AI\Packages\A1111\venv\lib\site-packages\polygraphy\logger\logger.py", line 605, in critical
    raise ExceptionType(message) from None
polygraphy.exception.exception.PolygraphyException: Failed to parse ONNX model. Does the model file exist and contain a valid ONNX model?
```
which i've gotten around it by force rebuilding a before 0.2.0 version trt model of the same checkpoint, another odd thing is that after you make one, you can make any other one just fine. also pytorch fallback is weird, you need double the batch size to make it function properly. Idk whats wrong so any help as to making a model (for the first time) in V 0.2.0 would be appreciated.

**Comment by Pista007** [comment]
Can anyone tell me the solution to this problem?

**Comment by Zer0xPoint** [comment]
me2

**Comment by Magicalife** [comment]
我尝试了安装PyTorch以后，重启电脑就解决了。
因为查资料翻阅到无法建立的原因和PyTorch有关，安装重启以后就可以运行了，我也不知道是不是和这个有关，毕竟不太懂变成。
如果你是中国用户并且用的是秋叶包，那你可以在启动页面--高级选项--环境维护里面有这个选项。
希望能帮到你。

**Comment by angelfor3v3r** [comment]
Is there still no solution for this? I've tried updating/downgrading and following tensorrt install instructions and I always seem to get the error. Is 0.2.0 just broken?

**Comment by Magicalife** [comment]
> Is there still no solution for this? I've tried updating/downgrading and following tensorrt install instructions and I always seem to get the error. Is 0.2.0 just broken?

With reference to my comments, I have solved it.

**Comment by angelfor3v3r** [comment]
> > Is there still no solution for this? I've tried updating/downgrading and following tensorrt install instructions and I always seem to get the error. Is 0.2.0 just broken?
> 
> With reference to my comments, I have solved it.

Sorry, I only speak English and translating is a bit hard. I'm using `webui-user.bat` to start my GUI, so I assume it has a specific version of pytorch installed, do I manually have to go in my venv and modify the version or can you provide me more details? Thanks!

**Comment by Heather95** [comment]
> > With reference to my comments, I have solved it.
> 
> Sorry, I only speak English and translating is a bit hard. I'm using `webui-user.bat` to start my GUI, so I assume it has a specific version of pytorch installed, do I manually have to go in my venv and modify the version or can you provide me more details? Thanks!

According to DeepL translator, they solved the problem after installing PyTorch and restarting the PC, which Chinese users can do via the Qiuye package software; but they're not sure if this has anything to do with the issue itself. 

Forge already has both torch and pytorch-lightning installed, but they are older versions, which technically could be updated (I haven't tried it yet myself). You could try `pip install torch` in commandline, or use the Python Packages manager in [Stability Matrix](https://github.com/LykosAI/StabilityMatrix) via the 3 dots on Forge. @angelfor3v3r

**Comment by psykokwak-com** [comment]
I made : 
```
venv\Scripts\activate.bat
python -m pip uninstall torch torchvision torchaudio  
python -m pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121 
webui-user.bat
```

But it does not fix the issue : 
ERROR:root:Exporting to ONNX failed. Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0! (when checking argument for argument mat1 in method wrapper_CUDA_addmm)
polygraphy.exception.exception.PolygraphyException: Failed to parse ONNX model. Does the model file exist and contain a valid ONNX model?
Interrupted with signal 2 in <frame at 0x000001CA4D3F2B00, file 'C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python310\\lib\\threading.py', line 324, code wait>

**Comment by angelfor3v3r** [comment]
> What size are you guys trying to export, when the ONXX model error appears?
> 
> I fixed this issue by exporting the ABSOLUTE MINIMUM resolution that I can of a model first, 1 batch size. This can use almost no VRAM, leaving all of it for the ONNX export at first.
> 
> After that, the ONNX is present, so you can export any other resolution that you would like. (IF, and ONLY IF you managed to export it with the previous step.)
> 
> It's a dumb workaround, but it worked for me.

I was just using defaults or normal SDXL resolutions. I see your posts about VRAM usage being high, but I don't see any spikes in my VRAM at all, it just errors right away. I'll try your workaround, thanks!

**Comment by eav-solution** [comment]
I cannot imagine that this is repo from 2000B dollars company :D No one support, hello some body here...

**Comment by caoddgao** [comment]
mwt the same problem

**Comment by Heather95** [comment]
None of the workarounds fixed the issue for me either, guys. Thanks T9es, though, for offering the suggestion.

Have any of you tried the controlnet-v2 or developer branch? Apparently, they have some more fixes than main, but I haven't tried them.
Also, I've seen in other issues, a suggestion to run your UI as administrator. @angelfor3v3r

**Comment by psykokwak-com** [comment]
I make it working usint the controlnet_v2 branch!

I made some benchmark on my computer (RTX4090) and here what I got : 
- SDXL 1024x1024, 20 samples, w/o tensorRT : 5.9sec
- SDXL 1024x1024, 20 samples, w/ tensorRT : 3.9sec
- SDXL Lightining 1024x1024, 6 samples, w/o tensorRT : 2.0sec
- SDXL Lightining 1024x1024, 6 samples, w/ tensorRT : 1.4sec

**Comment by ceoper** [comment]
I can temporarily bypass this error by only using GPU.
I'm using stable-diffusion-webui-forge and this UI provides an option: `--always-gpu`,
but I'm new to stable diffusion so I don't know how to do the same with other UIs.

**Comment by Ruikesan** [comment]
I was getting the same error today at all sizes and parameters, but I got it to work by removing --xformers in the startup config, so for me it is blank. Also, in the webui settings under optimizations I have:
Cross attention optimization: Automatic
0 for all the sliders (Neg. Guidance and all 3 Token Merging)

✅Pad prompt/negative prompt
⬛Pad prompt/negative prompt (v0)
✅Persistent cond cache
✅Batch cond/uncond

FP8 weight
Disable
⬛Cache FP16 weight for LoRA

Hope this helps

**Comment by aearone** [comment]
If you get this error after installing the TensorRT Extension, just remove any parameters in COMMANDLINE_ARGS, it worked for me.

**Comment by Overwatchyourmouth** [comment]
秋叶整合包：主界面-高级选项-网络设置，不勾选启用API，问题解决。
do not use API, it works.
20240404

**Comment by uni-devboy** [comment]
None of the above worked for me, this is what worked for me and fixed it to export engines with SD Forge
https://github.com/lllyasviel/stable-diffusion-webui-forge/issues/64#issuecomment-2001987142

**Comment by silverace71** [comment]
figured it out guys, its SDXL specific i think, but heres the steps in order. Delete the tensorrt extension from your extension folder, restart, install the dev branch, stop the instance (dont restart, just stop your instance or close out of it), then delete your venv file and start your A1111 instance. Worked for me (made a 768x1344 version and it took a little bit but just leave it running)!

**Comment by denierus31** [comment]
In stable diffusion, it works without errors with some checkpoints, but an error occurs on some another checkpoints. For example, there is no error with revAnimated_v122EOL or with Flat-2D_Animerge_v45Sharp, but with absolutereality_v181 this error appears.

**Comment by Kaiten10** [comment]
Using --lowvram fixed it for me.
Since the error message says it found two devices (cpu and cuda:0), I think --lowvram fixed it by forcing SD to only use the CPU.

**Comment by hkpD** [comment]
Disabling the HyperTile extension in A1111 settings fixed it for me

**Comment by Aragamin** [comment]
> Using --lowvram fixed it for me. Since the error message says it found two devices (cpu and cuda:0), I think --lowvram fixed it by forcing SD to only use the CPU.

Thank you, the engine has been created.
But, no, the GPU is still used, but for lowvram it’s about ~6GB...

**Comment by Eugeniusz-Gienek** [comment]
For me the fix was weird and simple. I just killed webui.sh, then started it over, then selected in the Unet dropdown in A1111 "None" and then the export magically worked.

**Comment by OscarPindaro** [comment]
> Using --lowvram fixed it for me. Since the error message says it found two devices (cpu and cuda:0), I think --lowvram fixed it by forcing SD to only use the CPU.

This worked for me on a RTX 4070 12GB on a pony model

**Comment by zanzan1235** [comment]
Hey guys, --lowvram,--midvram,--api, these three commands are not allowded during engine generating,just remove these,that can fix these problem.

**Comment by zanzan1235** [comment]
> Hey guys, --lowvram,--midvram,--api, these three commands are not allowded during engine generating,just remove these,that can fix these problem.

and this can explain why"--lowvram"can fix this problem.

**Comment by Vinzelles** [comment]
[ui_trt.txt](https://github.com/user-attachments/files/17674511/ui_trt.txt)
[exporter.txt](https://github.com/user-attachments/files/17674516/exporter.txt)

This is the solution I saw elsewhere.
I copied the codes in these two txt files to the .py files with the same name under "MY_WEBUI_PATH\extensions\Stable-Diffusion-WebUI-TensorRT" and replaced them, the problem was solved.
I don't know much about Python, if anyone knows how this works, please comment below.

**Comment by iftikharmehdi-metex** [comment]
I found a solution, First generate trt using the first present 256x256 - 512x512 | Batch Size 1-4. Then generate using other presets.

Without generating from the first preset it gives polygraphy.exception.exception.PolygraphyException: Failed to parse ONNX model. Does the model file exist and contain a valid ONNX model?

Strange, but worked for me

**Comment by anuo24601** [comment]
> I found a solution, First generate trt using the first present 256x256 - 512x512 | Batch Size 1-4. Then generate using other presets.
> 
> Without generating from the first preset it gives polygraphy.exception.exception.PolygraphyException: Failed to parse ONNX model. Does the model file exist and contain a valid ONNX model?
> 
> Strange, but worked for me

it does work!!
Thanks a lot!
