### ISSUE TITLE
OutOfMemory during engine generation process

### ISSUE THREAD

**Issue by Mohsyn** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#278]
RTX 4060 6GB RAM with 16GB System RAM
cmdline arguments: --ilsten --xformers

WebUI Engine geneartion process exits with following error:

Disabling attention optimization
Exporting sdxl_main_morphXL_morphxl_v10 to TensorRT using - Batch Size: 1-1-1
Height: 1024-1024-1024
Width: 1024-1024-1024
Token Count: 75-75-75
Disabling attention optimization
Building TensorRT engine... This can take a while, please check the progress in the terminal.
Building TensorRT engine for C:\stable-diffusion-webui\webui\models\Unet-onnx\sdxl_main_morphXL_morphxl_v10.onnx: C:\stable-diffusion-webui\webui\models\Unet-trt\sdxl_main_morphXL_morphxl_v10_ff92ec92_cc89_sample=2x4x128x128+2x4x128x128+2x4x128x128-timesteps=2+2+2-encoder_hidden_states=2x77x2048+2x77x2048+2x77x2048-y=2x2816+2x2816+2x2816.trt
[W] 'colored' module is not installed, will not use colors when logging. To enable colors, please install the 'colored' module: python3 -m pip install colored
[E] 1: [myelinCache.cpp::nvinfer1::builder::MyelinAutotunerCache::deserialize::62] Error Code 1: Myelin (Myelin error from unknown graph)
[E] 4: The timing cache will not be used!
Building engine:  50%|█████████████████████████████████▌                                 | 3/6 [06:22<00:00, 13.95it/s][E] 2: [virtualMemoryBuffer.cpp::nvinfer1::StdVirtualMemoryBufferImpl::resizePhysical::140] Error Code 2: OutOfMemory (no further information)ts:   0%|                                                                   | 0/5 [06:20<?, ?it/s]
[E] 1: [virtualMemoryBuffer.cpp::nvinfer1::StdVirtualMemoryBufferImpl::resizePhysical::127] Error Code 1: Cuda Driver (invalid argument)
Building engine:  50%|█████████████████████████████████▌                                 | 3/6 [06:56<00:00, 13.95it/s]Press any key to continue . . .   0%|                                                             | 0/1 [06:54<?, ?it/s]

__________________________

Any help to resolve this issue is appreciated. Thanks!

**Comment by banjaminicc** [comment]
6GB is probably just not enough for SDXL
