### ISSUE TITLE
Error with SDXL Lora

### ISSUE THREAD

**Issue by DennLie** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#32]
I switched to dev branch and SDXL works. However When# i try to convert my trained SDXL Lora i get errors.
.
.
.
Add Constant /output_blocks.5/output_blocks.5.1/transformer_blocks.1/attn2/Constant_31_output_0

ERROR:root:Failed to add Constant /output_blocks.5/output_blocks.5.1/transformer_blocks.1/attn2/Constant_31_output_0

Add Constant /output_blocks.5/output_blocks.5.1/transformer_blocks.1/attn2/Constant_32_output_0

ERROR:root:Failed to add Constant /output_blocks.5/output_blocks.5.1/transformer_blocks.1/attn2/Constant_32_output_0

Add Constant /output_blocks.5/output_blocks.5.1/transformer_blocks.1/attn2/Constant_33_output_0

ERROR:root:Failed to add Constant /output_blocks.5/output_blocks.5.1/transformer_blocks.1/attn2/Constant_33_output_0

Add Constant /output_blocks.5/output_blocks.5.1/transformer_blocks.1/attn2/Constant_34_output_0

ERROR:root:Failed to add Constant /output_blocks.5/output_blocks.5.1/transformer_blocks.1/attn2/Constant_34_output_0

Add Constant onnx::Unsqueeze_33460

ERROR:root:Failed to add Constant onnx::Unsqueeze_33460

Add Constant /output_blocks.5/output_blocks.5.1/transformer_blocks.1/attn2/Constant_35_output_0

ERROR:root:Failed to add Constant /output_blocks.5/output_blocks.5.1/transformer_blocks.1/attn2/Constant_35_output_0

Add Constant onnx::Unsqueeze_33464

ERROR:root:Failed to add Constant onnx::Unsqueeze_33464

Add Constant onnx::Unsqueeze_33466

ERROR:root:Failed to add Constant onnx::Unsqueeze_33466

Add Constant onnx::Unsqueeze_33471

ERROR:root:Failed to add Constant onnx::Unsqueeze_33471

Add Constant onnx::Unsqueeze_33473

ERROR:root:Failed to add Constant onnx::Unsqueeze_33473

Add Constant onnx::Unsqueeze_33475

ERROR:root:Failed to add Constant onnx::Unsqueeze_33475

Add Constant /output_blocks.5/output_blocks.5.1/transformer_blocks.1/ff/net/net.0/Constant_output_0

ERROR:root:Failed to add Constant /output_blocks.5/output_blocks.5.1/transformer_blocks.1/ff/net/net.0/Constant_output_0

Add Constant /output_blocks.5/output_blocks.5.1/transformer_blocks.1/ff/net/net.0/Constant_1_output_0

ERROR:root:Failed to add Constant /output_blocks.5/output_blocks.5.1/transformer_blocks.1/ff/net/net.0/Constant_1_output_0

Add Constant /output_blocks.5/output_blocks.5.1/transformer_blocks.1/ff/net/net.0/Constant_2_output_0

ERROR:root:Failed to add Constant /output_blocks.5/output_blocks.5.1/transformer_blocks.1/ff/net/net.0/Constant_2_output_0

Add Constant /output_blocks.5/output_blocks.5.1/transformer_blocks.1/ff/net/net.0/Constant_3_output_0

ERROR:root:Failed to add Constant /output_blocks.5/output_blocks.5.1/transformer_blocks.1/ff/net/net.0/Constant_3_output_0

Add Constant /output_blocks.5/output_blocks.5.1/transformer_blocks.1/ff/net/net.0/Constant_4_output_0

ERROR:root:Failed to add Constant /output_blocks.5/output_blocks.5.1/transformer_blocks.1/ff/net/net.0/Constant_4_output_0

Add Constant /output_blocks.5/output_blocks.5.1/transformer_blocks.1/ff/net/net.0/Constant_5_output_0

ERROR:root:Failed to add Constant /output_blocks.5/output_blocks.5.1/transformer_blocks.1/ff/net/net.0/Constant_5_output_0

Add Constant /output_blocks.5/output_blocks.5.1/transformer_blocks.1/ff/net/net.0/Constant_6_output_0

ERROR:root:Failed to add Constant /output_blocks.5/output_blocks.5.1/transformer_blocks.1/ff/net/net.0/Constant_6_output_0

Add Constant /output_blocks.5/output_blocks.5.1/transformer_blocks.1/ff/net/net.0/Constant_7_output_0

ERROR:root:Failed to add Constant /output_blocks.5/output_blocks.5.1/transformer_blocks.1/ff/net/net.0/Constant_7_output_0

Add Constant /output_blocks.5/output_blocks.5.1/transformer_blocks.1/ff/net/net.0/Constant_8_output_0

ERROR:root:Failed to add Constant /output_blocks.5/output_blocks.5.1/transformer_blocks.1/ff/net/net.0/Constant_8_output_0

Add Constant /output_blocks.5/output_blocks.5.1/Constant_11_output_0

ERROR:root:Failed to add Constant /output_blocks.5/output_blocks.5.1/Constant_11_output_0

Add Constant /output_blocks.5/output_blocks.5.1/Constant_12_output_0

ERROR:root:Failed to add Constant /output_blocks.5/output_blocks.5.1/Constant_12_output_0

Add Constant /output_blocks.5/output_blocks.5.1/Constant_13_output_0

ERROR:root:Failed to add Constant /output_blocks.5/output_blocks.5.1/Constant_13_output_0

Add Constant /output_blocks.5/output_blocks.5.1/Constant_14_output_0

ERROR:root:Failed to add Constant /output_blocks.5/output_blocks.5.1/Constant_14_output_0

Add Constant onnx::Unsqueeze_33535

ERROR:root:Failed to add Constant onnx::Unsqueeze_33535

Add Constant onnx::Unsqueeze_33537

ERROR:root:Failed to add Constant onnx::Unsqueeze_33537

Add Constant onnx::Unsqueeze_33539

ERROR:root:Failed to add Constant onnx::Unsqueeze_33539

Add Constant onnx::Unsqueeze_33541

ERROR:root:Failed to add Constant onnx::Unsqueeze_33541

Add Constant onnx::Unsqueeze_33546

ERROR:root:Failed to add Constant onnx::Unsqueeze_33546

Add Constant onnx::Unsqueeze_33548

ERROR:root:Failed to add Constant onnx::Unsqueeze_33548

Add Constant onnx::Unsqueeze_33550

ERROR:root:Failed to add Constant onnx::Unsqueeze_33550

Add Constant onnx::Unsqueeze_33552

ERROR:root:Failed to add Constant onnx::Unsqueeze_33552

Add Constant /output_blocks.5/output_blocks.5.2/Constant_output_0

ERROR:root:Failed to add Constant /output_blocks.5/output_blocks.5.2/Constant_output_0

Add Constant /output_blocks.6/output_blocks.6.0/in_layers/in_layers.0/Constant_output_0

ERROR:root:Failed to add Constant /output_blocks.6/output_blocks.6.0/in_layers/in_layers.0/Constant_output_0

Add Constant /output_blocks.6/output_blocks.6.0/in_layers/in_layers.0/Constant_1_output_0

ERROR:root:Failed to add Constant /output_blocks.6/output_blocks.6.0/in_layers/in_layers.0/Constant_1_output_0

Add Constant /output_blocks.6/output_blocks.6.0/in_layers/in_layers.0/Constant_2_output_0

ERROR:root:Failed to add Constant /output_blocks.6/output_blocks.6.0/in_layers/in_layers.0/Constant_2_output_0

Add Constant /output_blocks.6/output_blocks.6.0/Constant_output_0

ERROR:root:Failed to add Constant /output_blocks.6/output_blocks.6.0/Constant_output_0

Add Constant /output_blocks.6/output_blocks.6.0/Constant_1_output_0

ERROR:root:Failed to add Constant /output_blocks.6/output_blocks.6.0/Constant_1_output_0

Add Constant /output_blocks.6/output_blocks.6.0/out_layers/out_layers.0/Constant_output_0

ERROR:root:Failed to add Constant /output_blocks.6/output_blocks.6.0/out_layers/out_layers.0/Constant_output_0

Add Constant /output_blocks.6/output_blocks.6.0/out_layers/out_layers.0/Constant_1_output_0

ERROR:root:Failed to add Constant /output_blocks.6/output_blocks.6.0/out_layers/out_layers.0/Constant_1_output_0

Add Constant /output_blocks.6/output_blocks.6.0/out_layers/out_layers.0/Constant_2_output_0

ERROR:root:Failed to add Constant /output_blocks.6/output_blocks.6.0/out_layers/out_layers.0/Constant_2_output_0

Add Constant /output_blocks.7/output_blocks.7.0/in_layers/in_layers.0/Constant_output_0

ERROR:root:Failed to add Constant /output_blocks.7/output_blocks.7.0/in_layers/in_layers.0/Constant_output_0

Add Constant /output_blocks.7/output_blocks.7.0/in_layers/in_layers.0/Constant_1_output_0

ERROR:root:Failed to add Constant /output_blocks.7/output_blocks.7.0/in_layers/in_layers.0/Constant_1_output_0

Add Constant /output_blocks.7/output_blocks.7.0/in_layers/in_layers.0/Constant_2_output_0

ERROR:root:Failed to add Constant /output_blocks.7/output_blocks.7.0/in_layers/in_layers.0/Constant_2_output_0

Add Constant /output_blocks.7/output_blocks.7.0/Constant_output_0

ERROR:root:Failed to add Constant /output_blocks.7/output_blocks.7.0/Constant_output_0

Add Constant /output_blocks.7/output_blocks.7.0/Constant_1_output_0

ERROR:root:Failed to add Constant /output_blocks.7/output_blocks.7.0/Constant_1_output_0

Add Constant /output_blocks.7/output_blocks.7.0/out_layers/out_layers.0/Constant_output_0

ERROR:root:Failed to add Constant /output_blocks.7/output_blocks.7.0/out_layers/out_layers.0/Constant_output_0

Add Constant /output_blocks.7/output_blocks.7.0/out_layers/out_layers.0/Constant_1_output_0

ERROR:root:Failed to add Constant /output_blocks.7/output_blocks.7.0/out_layers/out_layers.0/Constant_1_output_0

Add Constant /output_blocks.7/output_blocks.7.0/out_layers/out_layers.0/Constant_2_output_0

ERROR:root:Failed to add Constant /output_blocks.7/output_blocks.7.0/out_layers/out_layers.0/Constant_2_output_0

Add Constant /output_blocks.8/output_blocks.8.0/in_layers/in_layers.0/Constant_output_0

ERROR:root:Failed to add Constant /output_blocks.8/output_blocks.8.0/in_layers/in_layers.0/Constant_output_0

Add Constant /output_blocks.8/output_blocks.8.0/in_layers/in_layers.0/Constant_1_output_0

ERROR:root:Failed to add Constant /output_blocks.8/output_blocks.8.0/in_layers/in_layers.0/Constant_1_output_0

Add Constant /output_blocks.8/output_blocks.8.0/in_layers/in_layers.0/Constant_2_output_0

ERROR:root:Failed to add Constant /output_blocks.8/output_blocks.8.0/in_layers/in_layers.0/Constant_2_output_0

Add Constant /output_blocks.8/output_blocks.8.0/Constant_output_0

ERROR:root:Failed to add Constant /output_blocks.8/output_blocks.8.0/Constant_output_0

Add Constant /output_blocks.8/output_blocks.8.0/Constant_1_output_0

ERROR:root:Failed to add Constant /output_blocks.8/output_blocks.8.0/Constant_1_output_0

Add Constant /output_blocks.8/output_blocks.8.0/out_layers/out_layers.0/Constant_output_0

ERROR:root:Failed to add Constant /output_blocks.8/output_blocks.8.0/out_layers/out_layers.0/Constant_output_0

Add Constant /output_blocks.8/output_blocks.8.0/out_layers/out_layers.0/Constant_1_output_0

ERROR:root:Failed to add Constant /output_blocks.8/output_blocks.8.0/out_layers/out_layers.0/Constant_1_output_0

Add Constant /output_blocks.8/output_blocks.8.0/out_layers/out_layers.0/Constant_2_output_0

ERROR:root:Failed to add Constant /output_blocks.8/output_blocks.8.0/out_layers/out_layers.0/Constant_2_output_0

Add Constant /out/out.0/Constant_output_0

ERROR:root:Failed to add Constant /out/out.0/Constant_output_0

Add Constant /out/out.0/Constant_1_output_0

ERROR:root:Failed to add Constant /out/out.0/Constant_1_output_0

Add Constant /out/out.0/Constant_2_output_0

ERROR:root:Failed to add Constant /out/out.0/Constant_2_output_0

Finished refit. Dumping result to disk.
Traceback (most recent call last):
  File "A:\stable-diffusion-webui-dev\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "A:\stable-diffusion-webui-dev\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "A:\stable-diffusion-webui-dev\venv\lib\site-packages\gradio\blocks.py", line 1117, in call_function
    prediction = await utils.async_iteration(iterator)
  File "A:\stable-diffusion-webui-dev\venv\lib\site-packages\gradio\utils.py", line 350, in async_iteration
    return await iterator.__anext__()
  File "A:\stable-diffusion-webui-dev\venv\lib\site-packages\gradio\utils.py", line 343, in __anext__
    return await anyio.to_thread.run_sync(
  File "A:\stable-diffusion-webui-dev\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "A:\stable-diffusion-webui-dev\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "A:\stable-diffusion-webui-dev\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "A:\stable-diffusion-webui-dev\venv\lib\site-packages\gradio\utils.py", line 326, in run_sync_iterator_async
    return next(iterator)
  File "A:\stable-diffusion-webui-dev\venv\lib\site-packages\gradio\utils.py", line 695, in gen_wrapper
    yield from f(*args, **kwargs)
  File "A:\stable-diffusion-webui-dev\extensions\Stable-Diffusion-WebUI-TensorRT\ui_trt.py", line 299, in export_lora_to_trt
    engine.refit(onnx_base_path, onnx_lora_path, dump_refit_path=trt_lora_path)
  File "A:\stable-diffusion-webui-dev\extensions\Stable-Diffusion-WebUI-TensorRT\utilities.py", line 277, in refit
    save_file(
  File "A:\stable-diffusion-webui-dev\venv\lib\site-packages\safetensors\numpy.py", line 74, in save_file
    if not _is_little_endian(tensor):
  File "A:\stable-diffusion-webui-dev\venv\lib\site-packages\safetensors\numpy.py", line 167, in _is_little_endian
    byteorder = tensor.dtype.byteorder
AttributeError: 'NoneType' object has no attribute 'dtype'

Is it currently not possible or am i doing something wrong?

**Comment by Nicoolodion2** [comment]
Just because it works sometimes, that doesn't mean that it will always work...

**Comment by contentis** [comment]
I haven't encountered this issue yet. But it seems like the refitting is failing but I don't have an immediate answer. Generally LoRA support is not where I'd want it to be, and I hope to improve this in the future, but this might take some time.

**Comment by DennLie** [comment]
Tested around with other SDXL Loras and i get this error on every single one of them.

**Comment by contentis** [comment]
I'm sorry for this inconvenience. I need to scope the work required to fix this, and it might take a while until I get it fixed.

**Comment by DennLie** [comment]
no need to feel sorry. Thx for your work! I continued trying to get sdxl Loras to work but all failed. 1.5 loras work though.  Can you confirm that SDXL loras dont work at all in the moment?

**Comment by contentis** [comment]
I was able to reproduce this issue, but currently, I have no idea why....

**Comment by sahil1572** [comment]
Getting exact same issue , any update on this ?

**Comment by DennisBalkan** [comment]
same here, 


Add Constant /output_blocks.5/output_blocks.5.1/Constant_14_output_0

ERROR:root:Failed to add Constant /output_blocks.5/output_blocks.5.1/Constant_14_output_0

Add Constant onnx::Unsqueeze_33535

ERROR:root:Failed to add Constant onnx::Unsqueeze_33535

Add Constant onnx::Unsqueeze_33537

ERROR:root:Failed to add Constant onnx::Unsqueeze_33537

Add Constant onnx::Unsqueeze_33539

ERROR:root:Failed to add Constant onnx::Unsqueeze_33539

Add Constant onnx::Unsqueeze_33541

ERROR:root:Failed to add Constant onnx::Unsqueeze_33541

Add Constant onnx::Unsqueeze_33546

ERROR:root:Failed to add Constant onnx::Unsqueeze_33546

Add Constant onnx::Unsqueeze_33548

ERROR:root:Failed to add Constant onnx::Unsqueeze_33548

Add Constant onnx::Unsqueeze_33550

ERROR:root:Failed to add Constant onnx::Unsqueeze_33550

Add Constant onnx::Unsqueeze_33552

ERROR:root:Failed to add Constant onnx::Unsqueeze_33552

Add Constant /output_blocks.5/output_blocks.5.2/Constant_output_0

ERROR:root:Failed to add Constant /output_blocks.5/output_blocks.5.2/Constant_output_0

Add Constant /output_blocks.6/output_blocks.6.0/in_layers/in_layers.0/Constant_output_0

ERROR:root:Failed to add Constant /output_blocks.6/output_blocks.6.0/in_layers/in_layers.0/Constant_output_0

Add Constant /output_blocks.6/output_blocks.6.0/in_layers/in_layers.0/Constant_1_output_0

ERROR:root:Failed to add Constant /output_blocks.6/output_blocks.6.0/in_layers/in_layers.0/Constant_1_output_0

Add Constant /output_blocks.6/output_blocks.6.0/in_layers/in_layers.0/Constant_2_output_0

ERROR:root:Failed to add Constant /output_blocks.6/output_blocks.6.0/in_layers/in_layers.0/Constant_2_output_0

Add Constant /output_blocks.6/output_blocks.6.0/Constant_output_0

ERROR:root:Failed to add Constant /output_blocks.6/output_blocks.6.0/Constant_output_0

Add Constant /output_blocks.6/output_blocks.6.0/Constant_1_output_0

ERROR:root:Failed to add Constant /output_blocks.6/output_blocks.6.0/Constant_1_output_0

Add Constant /output_blocks.6/output_blocks.6.0/out_layers/out_layers.0/Constant_output_0

ERROR:root:Failed to add Constant /output_blocks.6/output_blocks.6.0/out_layers/out_layers.0/Constant_output_0

Add Constant /output_blocks.6/output_blocks.6.0/out_layers/out_layers.0/Constant_1_output_0

ERROR:root:Failed to add Constant /output_blocks.6/output_blocks.6.0/out_layers/out_layers.0/Constant_1_output_0

Add Constant /output_blocks.6/output_blocks.6.0/out_layers/out_layers.0/Constant_2_output_0

ERROR:root:Failed to add Constant /output_blocks.6/output_blocks.6.0/out_layers/out_layers.0/Constant_2_output_0

Add Constant /output_blocks.7/output_blocks.7.0/in_layers/in_layers.0/Constant_output_0

ERROR:root:Failed to add Constant /output_blocks.7/output_blocks.7.0/in_layers/in_layers.0/Constant_output_0

Add Constant /output_blocks.7/output_blocks.7.0/in_layers/in_layers.0/Constant_1_output_0

ERROR:root:Failed to add Constant /output_blocks.7/output_blocks.7.0/in_layers/in_layers.0/Constant_1_output_0

Add Constant /output_blocks.7/output_blocks.7.0/in_layers/in_layers.0/Constant_2_output_0

ERROR:root:Failed to add Constant /output_blocks.7/output_blocks.7.0/in_layers/in_layers.0/Constant_2_output_0

Add Constant /output_blocks.7/output_blocks.7.0/Constant_output_0

ERROR:root:Failed to add Constant /output_blocks.7/output_blocks.7.0/Constant_output_0

Add Constant /output_blocks.7/output_blocks.7.0/Constant_1_output_0

ERROR:root:Failed to add Constant /output_blocks.7/output_blocks.7.0/Constant_1_output_0

Add Constant /output_blocks.7/output_blocks.7.0/out_layers/out_layers.0/Constant_output_0

ERROR:root:Failed to add Constant /output_blocks.7/output_blocks.7.0/out_layers/out_layers.0/Constant_output_0

Add Constant /output_blocks.7/output_blocks.7.0/out_layers/out_layers.0/Constant_1_output_0

ERROR:root:Failed to add Constant /output_blocks.7/output_blocks.7.0/out_layers/out_layers.0/Constant_1_output_0

Add Constant /output_blocks.7/output_blocks.7.0/out_layers/out_layers.0/Constant_2_output_0

ERROR:root:Failed to add Constant /output_blocks.7/output_blocks.7.0/out_layers/out_layers.0/Constant_2_output_0

Add Constant /output_blocks.8/output_blocks.8.0/in_layers/in_layers.0/Constant_output_0

ERROR:root:Failed to add Constant /output_blocks.8/output_blocks.8.0/in_layers/in_layers.0/Constant_output_0

Add Constant /output_blocks.8/output_blocks.8.0/in_layers/in_layers.0/Constant_1_output_0

ERROR:root:Failed to add Constant /output_blocks.8/output_blocks.8.0/in_layers/in_layers.0/Constant_1_output_0

Add Constant /output_blocks.8/output_blocks.8.0/in_layers/in_layers.0/Constant_2_output_0

ERROR:root:Failed to add Constant /output_blocks.8/output_blocks.8.0/in_layers/in_layers.0/Constant_2_output_0

Add Constant /output_blocks.8/output_blocks.8.0/Constant_output_0

ERROR:root:Failed to add Constant /output_blocks.8/output_blocks.8.0/Constant_output_0

Add Constant /output_blocks.8/output_blocks.8.0/Constant_1_output_0

ERROR:root:Failed to add Constant /output_blocks.8/output_blocks.8.0/Constant_1_output_0

Add Constant /output_blocks.8/output_blocks.8.0/out_layers/out_layers.0/Constant_output_0

ERROR:root:Failed to add Constant /output_blocks.8/output_blocks.8.0/out_layers/out_layers.0/Constant_output_0

Add Constant /output_blocks.8/output_blocks.8.0/out_layers/out_layers.0/Constant_1_output_0

ERROR:root:Failed to add Constant /output_blocks.8/output_blocks.8.0/out_layers/out_layers.0/Constant_1_output_0

Add Constant /output_blocks.8/output_blocks.8.0/out_layers/out_layers.0/Constant_2_output_0

ERROR:root:Failed to add Constant /output_blocks.8/output_blocks.8.0/out_layers/out_layers.0/Constant_2_output_0

Add Constant /out/out.0/Constant_output_0

ERROR:root:Failed to add Constant /out/out.0/Constant_output_0

Add Constant /out/out.0/Constant_1_output_0

ERROR:root:Failed to add Constant /out/out.0/Constant_1_output_0

Add Constant /out/out.0/Constant_2_output_0

ERROR:root:Failed to add Constant /out/out.0/Constant_2_output_0

Finished refit. Dumping result to disk.
Traceback (most recent call last):
  File "C:\AI\SD\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\AI\SD\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "C:\AI\SD\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\AI\SD\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\AI\SD\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\AI\SD\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\AI\SD\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "C:\AI\SD\stable-diffusion-webui\extensions\Stable-Diffusion-WebUI-TensorRT\ui_trt.py", line 262, in export_lora_to_trt
    engine.refit(onnx_base_path, onnx_lora_path, dump_refit_path=trt_lora_path)
  File "C:\AI\SD\stable-diffusion-webui\extensions\Stable-Diffusion-WebUI-TensorRT\utilities.py", line 277, in refit
    save_file(
  File "C:\AI\SD\stable-diffusion-webui\venv\lib\site-packages\safetensors\numpy.py", line 74, in save_file
    if not _is_little_endian(tensor):
  File "C:\AI\SD\stable-diffusion-webui\venv\lib\site-packages\safetensors\numpy.py", line 167, in _is_little_endian
    byteorder = tensor.dtype.byteorder
AttributeError: 'NoneType' object has no attribute 'dtype'

**Comment by sansavision** [comment]
So this basically just got ignored? I am facing this too
