### ISSUE TITLE
After install when i run webui.bat i got a lot of errors and dont work!

### ISSUE THREAD

**Issue by merecesarchviz** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#34]
Hi

I update my rtx 4090 drivers to last version, I install the extension as indicated in the information, but then when i lunch the webui.bat i got a lot of windows window errors! and the extension dont work, any idea how to solve this? thks:

![image](https://i.ibb.co/QY3wBxj/1.jpg)
![image](https://i.ibb.co/0Dtx5cB/2.jpg)
![image](https://i.ibb.co/1dt33Dq/3.jpg)

**Comment by ProfessorMorbius** [comment]
I've got the same problem but I'm running 3080TI. Running Python version 3.10.6

**Comment by contentis** [comment]
This is caused by a failure in the installer. Workin on a fix right now. In the meantime you can follow these steps to fix: https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/issues/27#issuecomment-1767570566

**Comment by contentis** [comment]
Closing duplicates + Seems to be resolved.

**Comment by antoninononooono** [comment]
This one fixed it for me. I put it into my SD directory and double clicked it without:

https://github.com/JackEllie/TensorRTvenvfix.bat/releases/download/fix/TensorRT-novenv.bat
