### ISSUE TITLE
 Help ! : "No valid profile found. Please go to the TensorRT tab and generate an engine with the necessary profile."

### ISSUE THREAD

**Issue by PaoloNeoz** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#35]
Hi !
I start by saying that I'm not a power user and I don't edit code and stuff like that, even if I used to be a software developer 20 years ago ;-) Now I'm only a 48 yo photographer :-D

I just installed TensorRT inside my A1111 and managed to get rid of initial popup errors deleting "cudnn" folder in \venv\Lib\site-packages as mentioned in another post by @Altrue ...
I can create engines now. I created two of them for cyberrealistic and epicrealism, but when I try to use them to generate an image I get the error in title.
I paste below the entire  text from the console ...
Anyone can help ?

Thanks !
Paolo

> *** Error completing request
*** Arguments: ('task(e1km8uykyuzr5oq)', 'woman', 'bw, worst quality, low quality, (deformed, distorted, disfigured:1.3), poorly drawn, bad anatomy, wrong anatomy, extra limb, missing limb, floating limbs, (mutated hands and fingers:1.4), disconnected limbs, mutation, mutated, ugly, disgusting, blurry, amputation, cloned', [], 25, 'DPM++ 2M Karras', 1, 1, 7, 512, 512, True, 0.3, 2, '4x_NMKD-Superscale-SP_178000_G', 10, 0, 0, 'Use same checkpoint', 'Use same sampler', '', '', [], <gradio.routes.Request object at 0x000002628D1E4910>, 0, False, '', 0.8, 4049516876, False, -1, 0, 0, 0, False, False, {'ad_model': 'face_yolov8n.pt', 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_k_largest': 0, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_use_checkpoint': False, 'ad_checkpoint': 'Use same checkpoint', 'ad_use_vae': False, 'ad_vae': 'Use same VAE', 'ad_use_sampler': False, 'ad_sampler': 'DPM++ 2M Karras', 'ad_use_noise_multiplier': False, 'ad_noise_multiplier': 1, 'ad_use_clip_skip': False, 'ad_clip_skip': 1, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_module': 'inpaint_global_harmonious', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1, 'is_api': ()}, {'ad_model': 'None', 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_k_largest': 0, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_use_checkpoint': False, 'ad_checkpoint': 'Use same checkpoint', 'ad_use_vae': False, 'ad_vae': 'Use same VAE', 'ad_use_sampler': False, 'ad_sampler': 'DPM++ 2M Karras', 'ad_use_noise_multiplier': False, 'ad_noise_multiplier': 1, 'ad_use_clip_skip': False, 'ad_clip_skip': 1, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_module': 'inpaint_global_harmonious', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1, 'is_api': ()}, False, 'prompt keyword', 'keyword1, keyword2', 'None', 'textual inversion first', 'None', '0.7', 'None', True, False, 1, False, False, False, 1.1, 1.5, 100, 0.7, False, False, True, False, False, 0, 'Gustavosta/MagicPrompt-Stable-Diffusion', '', <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x000002628D180A60>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x000002628D1819C0>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x000002628D181780>, False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, False, 5, 'all', 'all', 'all', '', '', '', '1', 'none', False, '', '', 'comma', '', True, '', '20', 'all', 'all', 'all', 'all', 0, '', None, None, False, None, None, False, None, None, False, 50) {}
    Traceback (most recent call last):
      File "F:\A1111\stable-diffusion-webui\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "F:\A1111\stable-diffusion-webui\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "F:\A1111\stable-diffusion-webui\modules\txt2img.py", line 55, in txt2img
        processed = processing.process_images(p)
      File "F:\A1111\stable-diffusion-webui\modules\processing.py", line 732, in process_images
        res = process_images_inner(p)
      File "F:\A1111\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 42, in processing_process_images_hijack
        return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
      File "F:\A1111\stable-diffusion-webui\modules\processing.py", line 867, in process_images_inner
        samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
      File "F:\A1111\stable-diffusion-webui\modules\processing.py", line 1156, in sample
        return self.sample_hr_pass(samples, decoded_samples, seeds, subseeds, subseed_strength, prompts)
      File "F:\A1111\stable-diffusion-webui\modules\processing.py", line 1242, in sample_hr_pass
        samples = self.sampler.sample_img2img(self, samples, noise, self.hr_c, self.hr_uc, steps=self.hr_second_pass_steps or self.steps, image_conditioning=image_conditioning)
      File "F:\A1111\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 188, in sample_img2img
        samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
      File "F:\A1111\stable-diffusion-webui\modules\sd_samplers_common.py", line 261, in launch_sampling
        return func()
      File "F:\A1111\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 188, in <lambda>
        samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
      File "F:\A1111\stable-diffusion-webui\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "F:\A1111\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\sampling.py", line 594, in sample_dpmpp_2m
        denoised = model(x, sigmas[i] * s_in, **extra_args)
      File "F:\A1111\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "F:\A1111\stable-diffusion-webui\modules\sd_samplers_cfg_denoiser.py", line 169, in forward
        x_out = self.inner_model(x_in, sigma_in, cond=make_condition_dict(cond_in, image_cond_in))
      File "F:\A1111\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "F:\A1111\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\external.py", line 112, in forward
        eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
      File "F:\A1111\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\external.py", line 138, in get_eps
        return self.inner_model.apply_model(*args, **kwargs)
      File "F:\A1111\stable-diffusion-webui\modules\sd_hijack_utils.py", line 17, in <lambda>
        setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
      File "F:\A1111\stable-diffusion-webui\modules\sd_hijack_utils.py", line 28, in __call__
        return self.__orig_func(*args, **kwargs)
      File "F:\A1111\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 858, in apply_model
        x_recon = self.model(x_noisy, t, **cond)
      File "F:\A1111\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "F:\A1111\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 1335, in forward
        out = self.diffusion_model(x, t, context=cc)
      File "F:\A1111\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "F:\A1111\stable-diffusion-webui\modules\sd_unet.py", line 89, in UNetModel_forward
        return current_unet.forward(x, timesteps, context, *args, **kwargs)
      File "F:\A1111\stable-diffusion-webui\extensions\Stable-Diffusion-WebUI-TensorRT\scripts\trt.py", line 87, in forward
        self.switch_engine(feed_dict)
      File "F:\A1111\stable-diffusion-webui\extensions\Stable-Diffusion-WebUI-TensorRT\scripts\trt.py", line 108, in switch_engine
        raise ValueError(
    ValueError: No valid profile found. Please go to the TensorRT tab and generate an engine with the necessary profile. Or use the default (torch) U-Net.

**Comment by PaoloNeoz** [comment]
Ok I found a post that tells that we have to generate a specific profile for the target resolution if we use HIRES FIX.
Otherwise the generation will fail.

So if I disable HIRES FIX, that I always use, the generation works and I see an improvement from 14 it/s to 23 it/s with my 4070 TI.

But ... if I enable HIRES FIX to upscale 512*768 image to 1024*1536, even after the genration of a dedicated profile for 1024*1536, the generation speed does not increase by much (18.7 sec vs 17.9 sec using 150 sampling steps to better check the speed).
The iterations increses to 23 from 14 again but something works wrong appartently ...
The hires fix speed does not increase at all.

My profiles :
![Screenshot 2023-10-18 120404](https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/assets/148328647/dbeaf978-9bbf-4201-ae3d-b736e68fb120)

See console messages below (it seems like it is using the wrong profile ???) :

_0%|                                                                                                                                                                                                                                    | 0/150 [00:00<?, ?it/s]Loading TensorRT engine: F:\A1111\stable-diffusion-webui\models\Unet-trt\SD_cyberrealistic_v33_82b0d085_cc89_sample=1x4x64x64+2x4x64x64+8x4x96x96-timesteps=1+2+8-encoder_hidden_states=1x77x768+2x77x768+8x154x768.trt                    | 0/10 [00:00<?, ?it/s]
[I] Loading bytes from F:\A1111\stable-diffusion-webui\models\Unet-trt\SD_cyberrealistic_v33_82b0d085_cc89_sample=1x4x64x64+2x4x64x64+8x4x96x96-timesteps=1+2+8-encoder_hidden_states=1x77x768+2x77x768+8x154x768.trt
Profile 0:
        sample = [(1, 4, 64, 64), (2, 4, 64, 64), (8, 4, 96, 96)]
        timesteps = [(1,), (2,), (8,)]
        encoder_hidden_states = [(1, 77, 768), (2, 77, 768), (8, 154, 768)]
        latent = [(-1945884672), (-1945884160), (-1945878668)]

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 150/150 [00:09<00:00, 15.65it/s]
  0%|                                                                                                                                                                                                                                     | 0/10 [00:00<?, ?it/s]Loading TensorRT engine: F:\A1111\stable-diffusion-webui\models\Unet-trt\SD_cyberrealistic_v33_82b0d085_cc89_sample=2x4x192x128-timesteps=2-encoder_hidden_states=2x77x768.trt
[I] Loading bytes from F:\A1111\stable-diffusion-webui\models\Unet-trt\SD_cyberrealistic_v33_82b0d085_cc89_sample=2x4x192x128-timesteps=2-encoder_hidden_states=2x77x768.trt
Profile 0:
        sample = [(2, 4, 192, 128), (2, 4, 192, 128), (2, 4, 192, 128)]
        timesteps = [(2,), (2,), (2,)]
        encoder_hidden_states = [(2, 77, 768), (2, 77, 768), (2, 77, 768)]
        latent = [(2, 4, 192, 128), (2, 4, 192, 128), (2, 4, 192, 128)]

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:04<00:00,  2.23it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 160/160 [00:18<00:00,  8.83it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 160/160 [00:18<00:00,  3.25it/s]_

**Comment by contentis** [comment]
Hi, HIRES fix is something that I have not considered when developing this. Due to the engine having to be swapped in and out the overhead overshadows all performance gains.

This is something I need to address, but this will take some time.

**Comment by tyen0** [comment]
Maybe it can fall back to not using the tensorrt engine automatically if no matching profile found?  Faster trt first pass, normal hires fix, faster trt adetailer inpainting.  In the spirit of quality over quantity. :)

**Comment by contentis** [comment]
@tyen0 The limiting factor is reloading weights. Torch and TensorRT use different memory pools. Therefore you wouldn't see any performance benefit from that...

**Comment by contentis** [comment]
The dev branch contains a fix for the engine selection heuristic. It will now try to select an engine that covers both the hi and lowres. If it can't it will inform the user. 

Please not that this is still WIP and might have some bugs.

**Comment by thanayut1750** [comment]
> Ok I found a post that tells that we have to generate a specific profile for the target resolution if we use HIRES FIX. Otherwise the generation will fail.
> 
> So if I disable HIRES FIX, that I always use, the generation works and I see an improvement from 14 it/s to 23 it/s with my 4070 TI.
> 
> But ... if I enable HIRES FIX to upscale 512 x 768 image to 1024 x 1536, even after the genration of a dedicated profile for 1024*1536, the generation speed does not increase by much (18.7 sec vs 17.9 sec using 150 sampling steps to better check the speed). The iterations increses to 23 from 14 again but something works wrong appartently ... The hires fix speed does not increase at all.
> 
> My profiles : ![Screenshot 2023-10-18 120404](https://user-images.githubusercontent.com/148328647/276207969-dbeaf978-9bbf-4201-ae3d-b736e68fb120.png)
> 
> See console messages below (it seems like it is using the wrong profile ???) :
> 
> _0%| | 0/150 [00:00<?, ?it/s]Loading TensorRT engine: F:\A1111\stable-diffusion-webui\models\Unet-trt\SD_cyberrealistic_v33_82b0d085_cc89_sample=1x4x64x64+2x4x64x64+8x4x96x96-timesteps=1+2+8-encoder_hidden_states=1x77x768+2x77x768+8x154x768.trt | 0/10 [00:00<?, ?it/s] [I] Loading bytes from F:\A1111\stable-diffusion-webui\models\Unet-trt\SD_cyberrealistic_v33_82b0d085_cc89_sample=1x4x64x64+2x4x64x64+8x4x96x96-timesteps=1+2+8-encoder_hidden_states=1x77x768+2x77x768+8x154x768.trt Profile 0: sample = [(1, 4, 64, 64), (2, 4, 64, 64), (8, 4, 96, 96)] timesteps = [(1,), (2,), (8,)] encoder_hidden_states = [(1, 77, 768), (2, 77, 768), (8, 154, 768)] latent = [(-1945884672), (-1945884160), (-1945878668)]
> 
> 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 150/150 [00:09<00:00, 15.65it/s] 0%| | 0/10 [00:00<?, ?it/s]Loading TensorRT engine: F:\A1111\stable-diffusion-webui\models\Unet-trt\SD_cyberrealistic_v33_82b0d085_cc89_sample=2x4x192x128-timesteps=2-encoder_hidden_states=2x77x768.trt [I] Loading bytes from F:\A1111\stable-diffusion-webui\models\Unet-trt\SD_cyberrealistic_v33_82b0d085_cc89_sample=2x4x192x128-timesteps=2-encoder_hidden_states=2x77x768.trt Profile 0: sample = [(2, 4, 192, 128), (2, 4, 192, 128), (2, 4, 192, 128)] timesteps = [(2,), (2,), (2,)] encoder_hidden_states = [(2, 77, 768), (2, 77, 768), (2, 77, 768)] latent = [(2, 4, 192, 128), (2, 4, 192, 128), (2, 4, 192, 128)]
> 
> 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:04<00:00, 2.23it/s] Total progress: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 160/160 [00:18<00:00, 8.83it/s] Total progress: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 160/160 [00:18<00:00, 3.25it/s]_

this problem still exits



> The dev branch contains a fix for the engine selection heuristic. It will now try to select an engine that covers both the hi and lowres. If it can't it will inform the user.
> 
> Please not that this is still WIP and might have some bugs.

even switch to the dev branch and reinstall the extension
