### ISSUE TITLE
What exactly does "Optimal" mean?

### ISSUE THREAD

**Issue by carnivar10** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#45]
<img width="928" alt="ask2" src="https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/assets/141563521/5f38325e-fa6d-4e79-8eed-c8a04b79b384">

when l export a TensorRT-based Engine, I know exactly what Min/Max Width and Height are for, but I don't know what Optimal is, and I didn't find anything about it in the description on the right. Does anyone know anything about it?

**Comment by contentis** [comment]
Optimal is the config TensorRT will optimize for, whereas min and max only define the range in which it needs to be operable.
E.g. an engine compiled with optimal width/height set to 512, will perform best when running it at 512x512.

**Comment by carnivar10** [comment]
> Optimal is the config TensorRT will optimize for, whereas min and max only define the range in which it needs to be operable. E.g. an engine compiled with optimal width/height set to 512, will perform best when running it at 512x512.

Thanks for the answer!! So if I start my image at 512 and grow it to 2048, do I need 3 engines with Optimal set to 512, 1024, and 2048? how would you recommend setting Optimal?

**Comment by contentis** [comment]
Technically, you could do an engine with min=512, opt=1024, max=2048 that covers all cases. But performance will probably be suboptimal at 512 and 2048. How large the performance impact is going to be is hard to estimate. In that case, I'd recommend exporting multiple engines, using your most commonly used resolutions for optimal.

**Comment by carnivar10** [comment]
<img width="844" alt="base512" src="https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/assets/141563521/c3094c3f-04aa-44bf-9030-e427cd4fd8cd">
<img width="852" alt="base1024" src="https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/assets/141563521/bbf175ee-c872-48e9-ae19-2de2cb94a637">
<img width="848" alt="base2048" src="https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/assets/141563521/5734fe2f-3c70-4260-a5cc-2e4b15270e2f">

I tried changing the Optimal Width and Height to 512, 1024, and 2048, but it doesn't seem to make much of a difference (I did this by pressing Force Rebuild on TensorRT Export and then creating a new Engine)

**Comment by contentis** [comment]
TensorRT sometimes is more art than science. It could be that 2048 is so large that, at that point, it doesn't make a difference. For 1024 you can definitely see a performance delta between the opt=512 and opt=1024 engine. 

From your experience is 1.0x it/s slow?

**Comment by carnivar10** [comment]
The difference in speed between using TensorRT and not using TensorRT is clear, but it doesn't seem to be an optimal value (at low resolutions, the images are generated very quickly, so it may be that can't tell)
