### ISSUE TITLE
multi / specific gpu?

### ISSUE THREAD

**Issue by KirillSamoilenko** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#46]
Hey! So it took me a while to get SDXL working. I could use 1.6.0 release of webUI to generate engines for both 1.5 and SDXL, but couldn't do it on dev branch. I copied models on dev instance and got it working finally. Now the last challenge I'm on is this:

RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

I use two 3090s in SLI, without tensorRT i have two instances running together using this in .bat:
set CUDA_VISIBLE_DEVICES= 0, 1
set COMMANDLINE_ARGS=--device-id 1

or --device-id 0  for other instance.

Any advice to make it work specifically on second gpu? I can get it working on dev branch without these parameters on "main" gpu 0

**Comment by contentis** [comment]
Currently, multi-GPU is not supported. It will always assume to run on cuda device 0, which probably caused the illegal memory access. 

If you set CUDA_VISIBLE_DEVICES=1 and then launch webui it should work. But it will only work on one GPU at a time I assume.
Depending on how many users are interested in multi GPU I could scope it.

**Comment by KirillSamoilenko** [comment]
this worked, thanks!

**Comment by korziner** [comment]
Yes, many users are interested in multi GPU, please scope it.

**Comment by dadadaing10** [comment]
Hello, I used set CUDA_VISIBLE_DEVICES= 0, 1
set COMMANDLINE_ARGS=--device-id 1, but Stable Diffusion still shows error.

I paste the webui-user.bat parameters here:
@echo off
set PYTHON_CUDA_ALLOC_CONF=max_split_size_mb:32
setPYTHON=
set GIT=
setVENV_DIR=
set COMMANDLINE_ARGS=--medvram --precision full --no-half --opt-sub-quad-attention --opt-split-attention-v1 --disable-nan-check
setCUDA_VISIBLE_DEVICES= 0, 1
set COMMANDLINE_ARGS=--device-id 1

call webui.bat

Thanks
<img width="434" alt="webui-user bat" src="https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/assets/51351847/577f200a-d602-460b-a767-025d1e47574e">
<img width="433" alt="webui bat" src="https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/assets/51351847/7af07939-93fc-4c8e-9ee1-d608f4dbbe18">
![Stable Diffusion](https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/assets/51351847/421c83ff-1e19-4492-80ff-d6ea53a8bcb5)
