### ISSUE TITLE
Comfyui Support?

### ISSUE THREAD

**Issue by FizzleDorf** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#5]
Hello, I would like to request a ComfyUI repo that makes using TensorRT easier to use with ComfyUI rather than CLI args. I think this would be beneficial especially for benchmark tests as A1111 isn't well optimized for inference (it's actually the worst out of the ui bunch). I think your analytics would get better numbers making this switch.  Thanks in advance for your input.

**Comment by NeedsMoar** [comment]
I agree but it looks like there might be some rather severe limitations.  I'm seeing the same lora getting associated with the base model type issue shark had except instead of every checkpoint needing its own program every base model and combination of loras would need one.  I'm not sure if I misread that or not.

**Comment by contentis** [comment]
For now there are no plans to support comfyui. But feel free to use this code to implement an extension for it. I'm happy to help, but I can't take this on at the moment.

**Comment by phineas-pta** [comment]
comfyanon already planned it but not high priority

comfyanonymous/ComfyUI#29

comfyanonymous/ComfyUI#1775

**Comment by phineas-pta** [comment]
advanced users can try my node: https://github.com/phineas-pta/comfy-trt-test

**Comment by Nicoolodion2** [comment]
Stable fast has it implemented in a for me pretty smart way (There is also of course Stable fast also available which improves performances also a bit with fully compability to most things) But I haven't tried the other thing.
https://github.com/gameltb/ComfyUI_stable_fast

**Comment by Nicoolodion2** [comment]
Okay I just looked at the other "garbage" what the other user did (not garbage, but just an testing node like he said.) Stable fast has it more useful implemented so that it detects if it builds a new engine (for example if a lora is added which is there supported) and then builds and applies it.
