### ISSUE TITLE
torch/onnx error with certain models (aten::copy)

### ISSUE THREAD

**Issue by prusswan** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#52]
```
============= Diagnostic Run torch.onnx.export version 2.0.1+cu118 =============
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 1 ERROR ========================
ERROR: missing-standard-symbolic-function
=========================================
Exporting the operator 'aten::copy' to ONNX opset version 17 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues.
None
<Set verbose=True to see more details>

ERROR:root:Exporting the operator 'aten::copy' to ONNX opset version 17 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues.
```

**Comment by jlitz** [comment]
works with revanimated  and .15 trained models,  does not work with SDXL or variations atm

**Comment by prusswan** [comment]
> What model did you encounter this issue on?

it's a random error, my guess is that it could be related to non-English characters in model filename or memory issues. Someone also suggested to disable xformers to reduce the chance of ONNX errors

**Comment by abenzenering** [comment]
I don't know much about pytorch, etc, but I've consistently gotten this error:
` ValueError: Unsupported ONNX opset version: 17
`
since trying to install the extension last night. Is this related to the model I'm using?

**Comment by contentis** [comment]
Can you do a pip freeze and send your installed onnx version. My first assumption would be that you need to update onnx

**Comment by abenzenering** [comment]
Thanks for the super quick response:
`$ cat freeze.txt
absl-py==1.3.0
addict==2.4.0
aiohttp==3.8.3
aiosignal==1.2.0
antlr4-python3-runtime==4.9.3
anyio==3.6.2
async-timeout==4.0.2
attrs==22.1.0
basicsr==1.4.2
bcrypt==4.0.1
cachetools==5.2.0
certifi==2022.9.24
cffi==1.15.1
chardet==4.0.0
charset-normalizer==2.1.1
clean-fid==0.1.29
click==8.1.3
colorama==0.4.6
coloredlogs==15.0.1
contourpy==1.0.6
cryptography==38.0.3
cycler==0.11.0
diffusers==0.3.0
einops==0.4.1
facexlib==0.2.5
fairscale==0.4.4
fastapi==0.86.0
ffmpy==0.3.0
filelock==3.8.0
filterpy==1.4.5
flatbuffers==22.10.26
font-roboto==0.0.1
fonts==0.0.3
fonttools==4.38.0
frozenlist==1.3.1
fsspec==2022.10.0
future==0.18.2
gfpgan==1.3.8
gitdb==4.0.9
GitPython==3.1.27
google-auth==2.14.0
google-auth-oauthlib==0.4.6
gradio==3.9
grpcio==1.50.0
h11==0.12.0
httpcore==0.15.0
httpx==0.23.0
huggingface-hub==0.10.1
humanfriendly==10.0
idna==2.10
imageio==2.22.3
importlib-metadata==5.0.0
inflection==0.5.1
invisible-watermark==0.1.5
Jinja2==3.1.2
jsonmerge==1.8.0
jsonschema==4.17.0
kiwisolver==1.4.4
kornia==0.6.7
lark==1.1.2
linkify-it-py==1.0.3
llvmlite==0.39.1
lmdb==1.3.0
Markdown==3.4.1
markdown-it-py==2.1.0
MarkupSafe==2.1.1
matplotlib==3.6.2
mdit-py-plugins==0.3.1
mdurl==0.1.2
mpmath==1.2.1
multidict==6.0.2
networkx==2.8.8
numba==0.56.4
numpy==1.23.3
nvidia-cublas-cu11==2022.4.8
nvidia-cublas-cu117==11.10.1.25
nvidia-cuda-nvrtc-cu11==2022.4.8
nvidia-cuda-nvrtc-cu117==11.7.50
nvidia-cuda-runtime-cu11==2022.4.25
nvidia-cuda-runtime-cu117==11.7.60
nvidia-pyindex==1.0.9
oauthlib==3.2.2
omegaconf==2.2.3
onnx==1.12.0
onnx-graphsurgeon==0.3.27
onnxruntime==1.13.1
opencv-python==4.6.0.66
orjson==3.8.1
packaging==21.3
pandas==1.5.1
paramiko==2.12.0
piexif==1.1.3
Pillow==9.2.0
protobuf==3.19.6
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.21
pycryptodome==3.15.0
pydantic==1.10.2
pyDeprecate==0.3.2
pydub==0.25.1
PyNaCl==1.5.0
pyparsing==3.0.9
pyreadline3==3.4.1
pyrsistent==0.19.2
python-dateutil==2.8.2
python-multipart==0.0.5
pytorch-lightning==1.7.7
pytz==2022.6
PyWavelets==1.4.1
PyYAML==6.0
realesrgan==0.3.0
regex==2022.10.31
requests==2.25.1
requests-oauthlib==1.3.1
resize-right==0.0.2
rfc3986==1.5.0
rsa==4.9
scikit-image==0.19.2
scipy==1.9.3
six==1.16.0
smmap==5.0.0
sniffio==1.3.0
starlette==0.20.4
sympy==1.11.1
tb-nightly==2.11.0a20221106
tensorboard==2.10.1
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.1
tensorrt==9.0.1.post11.dev4
tensorrt-bindings==9.0.1.post11.dev4
tensorrt-libs==9.0.1.post11.dev4
tifffile==2022.10.10
timm==0.4.12
tokenizers==0.12.1
torch==1.13.0
torchdiffeq==0.2.3
torchmetrics==0.10.2
torchvision==0.14.0
tqdm==4.64.1
transformers==4.19.2
typing_extensions==4.4.0
uc-micro-py==1.0.1
urllib3==1.26.12
uvicorn==0.19.0
websockets==10.4
Werkzeug==2.2.2
yapf==0.32.0
yarl==1.8.1
zipp==3.10.0
`

**Comment by contentis** [comment]
Could you try running `pip install onnx --upgrade`

**Comment by abenzenering** [comment]
Seems it updated:
`Successfully installed onnx-1.14.1 protobuf-4.24.4
`
I restarted a1111, but still get the same error though.

**Comment by contentis** [comment]
What model are you using? I'm best guessing at this point, as this seems to be a torch onnx related issue.

**Comment by abenzenering** [comment]
sd 1.5 (v1-5-pruned-emaonly.ckpt [cc6cb27103])

I appreciate the help so far... I'll keep poking around, don't want to waste your time. Thanks!

**Comment by jlitz** [comment]
I have the same model  and it works fine

**Comment by abenzenering** [comment]
Must be something I already had installed in the past mucking it up... I updated exporter.py to set opset=14 under export_onnx, and it works now.

**Comment by jlitz** [comment]
can always delete and start over  do a clean install of 1111 in another directory with just this extension

**Comment by tetsuoo-online** [comment]
> Must be something I already had installed in the past mucking it up... I updated exporter.py to set opset=14 under export_onnx, and it works now.

What does it do ? For me it was already at 17, changing it to 14 didn't change anything (not that I know what I'm doing)
