### ISSUE TITLE
UI can failed to load due to LoRA model missing metadata or none safetensors filetypes

### ISSUE THREAD

**Issue by w-e-w** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#6]
PR https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/pull/1
non-catched exception with get_lora_checkpoints()
AssertionError when non safetensors filetypes
TypeError ss_sd_model_name is None

in webui using extra networks tab we allow user to manually set what the type of lora model
the information is stored beside the model under the same name but with .json extension
we do this in webui because some older models or non safetensors does not have the metadata

so the the order of retrieving the version information should be
lora_model_name.json > safetensors metadata > "unknow"

**Comment by contentis** [comment]
This should be caught since #1 has been merged. I opened #36 to track the suggested enhancement.
