### ISSUE TITLE
Multiple profiles in one checkpoint?

### ISSUE THREAD

**Issue by carnivar10** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#62]
<img width="292" alt="multi profile" src="https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/assets/141563521/5228a575-b785-4907-8bc4-9087ac3057c3">

I've noticed that using the Export Engine by changing options in one checkpoint creates multiple profiles, so if I specify multiple Optimal Width/Height, will the profile automatically change to create an image whenever the resolution changes?

**Comment by contentis** [comment]
Yes, the current logic selects engines on 
1. How close is the requested resolution to the optimal resolution of an engine
2. If multiple engines have the same score, select the one with the least VRAM consumption.

**Comment by carnivar10** [comment]
Thanks for the clarification, If the extension automatically changes the optimal resolution, is it possible to add the ability to set multiple resolutions and generate them at once when using the 'Export Engine'? I think that would be really useful.

**Comment by contentis** [comment]
This has been asked in #60 as well. Currently, there is no support to export multiple checkpoints or profiles at once.

**Comment by Poukpalaova** [comment]
I've created multiple Profile for a SD 1.5, but when I change the resolution to match another profile, in the console I still see it take the Profile 0. 
How can I switch between profile? 
I have a 4090 video card with latest drivers (545.84)
The first picture asked, was batch 4, 512x512, 1 word in positive prompt
And in the 2 picture asked, same as 1 but with an upscale to x2 that lead to a 1024x1024 that should have take my profile 3:

Loading TensorRT engine: F:\IMAGES\AIgenerated\SDXL 1.6\stable-diffusion-webui\models\Unet-trt\photon_v1_d902a082_cc89_sample=1x4x64x64+2x4x64x64+8x4x96x96-timesteps=1+2+8-encoder_hidden_states=1x77x768+2x77x768+8x154x768.trt
[I] Loading bytes from F:\IMAGES\AIgenerated\SDXL 1.6\stable-diffusion-webui\models\Unet-trt\photon_v1_d902a082_cc89_sample=1x4x64x64+2x4x64x64+8x4x96x96-timesteps=1+2+8-encoder_hidden_states=1x77x768+2x77x768+8x154x768.trt
Profile 0:
        sample = [(1, 4, 64, 64), (2, 4, 64, 64), (8, 4, 96, 96)]
        timesteps = [(1,), (2,), (8,)]
        encoder_hidden_states = [(1, 77, 768), (2, 77, 768), (8, 154, 768)]
        latent = [(-1945914624), (-1945909504), (-1945910272)]

100%|█████████████████████████████████████████████████████████████████████████████████| 20/20 [00:04<00:00,  4.79it/s]
Total progress: 100%|█████████████████████████████████████████████████████████████████| 20/20 [00:01<00:00, 10.12it/s]
100%|█████████████████████████████████████████████████████████████████████████████████| 20/20 [00:01<00:00, 13.27it/s]
Total progress: 100%|█████████████████████████████████████████████████████████████████| 20/20 [00:02<00:00,  9.66it/s]
100%|█████████████████████████████████████████████████████████████████████████████████| 20/20 [00:01<00:00, 12.42it/s]
  0%|                                                                                          | 0/20 [00:00<?, ?it/s]Loading TensorRT engine: F:\IMAGES\AIgenerated\SDXL 1.6\stable-diffusion-webui\models\Unet-trt\photon_v1_d902a082_cc89_sample=1x4x64x64+2x4x128x128+8x4x128x128-timesteps=1+2+8-encoder_hidden_states=1x77x768+2x77x768+8x154x768.trt
[I] Loading bytes from F:\IMAGES\AIgenerated\SDXL 1.6\stable-diffusion-webui\models\Unet-trt\photon_v1_d902a082_cc89_sample=1x4x64x64+2x4x128x128+8x4x128x128-timesteps=1+2+8-encoder_hidden_states=1x77x768+2x77x768+8x154x768.trt
Profile 0:
        sample = [(1, 4, 64, 64), (2, 4, 128, 128), (8, 4, 128, 128)]
        timesteps = [(1,), (2,), (8,)]
        encoder_hidden_states = [(1, 77, 768), (2, 77, 768), (8, 154, 768)]
        latent = [(-1945966336), (-1945972992), (-1945967872)]

100%|█████████████████████████████████████████████████████████████████████████████████| 20/20 [00:14<00:00,  1.41it/s]
Total progress: 100%|█████████████████████████████████████████████████████████████████| 40/40 [00:23<00:00,  1.69it/s]
Total progress: 100%|█████████████████████████████████████████████████████████████████| 40/40 [00:23<00:00,  1.76it/s]
