### ISSUE TITLE
sdxl generatingerror

### ISSUE THREAD

**Issue by abozahran** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#72]
Made SDXL MODEL successfully
BUT GENERATING FAILING

this is the error message beneath preview window (NameError: name 'scaled_dot_product_attention' is not defined)

![image](https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/assets/107565623/32c221c4-0118-40fe-b454-cd1c6116a03e)
![image](https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/assets/107565623/541e5971-879d-46cf-a21c-bd536f896a7d)

**Comment by contentis** [comment]
Can you try restarting the app?

**Comment by arch1v1st** [comment]
@contentis - I hit this bug too after Exporting a new TensorRT engine.  Restarting the app fixed it for me!  Thanks.
