### ISSUE TITLE
LoRA Functionality and Weight Adjustment

### ISSUE THREAD

**Issue by EtienneDosSantos** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#74]
How are engines with LoRAs supposed to work? It appears they are baked into the engine. However, in my experience, utilizing the U-Net with an integrated LoRA doesn’t result in any discernible impact, even when I specifically include the LoRA in the positive prompt. 

This is an excerpt from the Nvidia guide on "TensorRT Extension for Stable Diffusion Web UI":
> ### LoRA (Experimental)
>
> To use LoRA checkpoints with TensorRT, follow these steps:
>
> 1. Install the checkpoints as you normally would.
> 2. Open the TensorRT Extension and navigate to the LoRA tab.
>   
>     a. Select an available LoRA checkpoint from the dropdown menu.
>     b. Click on the "Export" button to export the model. This should take about a minute.
>
> 3. Go back to the main UI, and select the LoRA checkpoint from the `sd_unet` dropdown menu.

This ultra-small section on LoRAs doesn't help much. Does anybody know how LoRAs are actually supposed to function in this extension? Additionally, how can I adjust the weights, and is it currently possible to use more than one LoRA?

**Comment by Priestru** [comment]
Basically this thingy doesn't work with RT.

https://github.com/hako-mikan/sd-webui-lora-block-weight

It would be nice to make list of limitations a little bit more comprehensive, so every new user would know what to expect.

**Comment by ThisIsNetsu** [comment]
So adding a LoRA works, BUT you can only ever activate a single LoRA at a time and you have to build a new TRT model for each? Hm. As much as I love the speedup, this limitation heavily reduces the usefulness at the moment.

**Comment by devjo** [comment]
> how can I adjust the weights, and is it currently possible to use more than one LoRA?

You can't

The LoRA seems to be fused into the checkpoint weights at strength 1.0 at present, and you can only fuse one LoRA.
I agree that it limits the usefulness immensely at present. I regard it as a tech preview atm. The author has mentioned some thoughts on how to make it more configurable going forward, but those options seem to all revolve around fused LoRAs with checlpoint weights.

I assume it's something to do with the TensorRT architecture, where it doesn't allow any kind of runtime adjustment to weights. I've seen the same limitation in TopazLabs products, where they're forced to generate terabytes of TensorRT checkpoints for every permutation of configurations _their_ apps support. And they've been at this for over a year now with no better solution found. That to me conveys runtime fusing of LoRAs is not something we should be expecting from this extension.

Still, even with this nVidia limitation, I'd be OK with having to specify a specific weight per LoRA at conversion time.
My workflow is to play around with my non-tensorrt checkpoints and LoRAs until I find a good set of hyper parameters to use for mass generation. Then I let SD WebUI generate a gazillion images with that configuration.

If this extension was simply improved to allow _configuring the Lora weight_ at conversion time, it'd start providing some real tangible value to my workflow.
