### ISSUE TITLE
python.exe entry point not found

### ISSUE THREAD

**Issue by Bananamax** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#78]
Greetings.
So far Stable Diffusion worked fine. I tried to install the TensorRT now. I installed it via the url and it seemed to work. I then restarted the ui. On startup it says (its german):
[https://ibb.co/XWQqssW](url)

I can then still start the web-ui interface and generate images. I cant find any mentioning of a TensorRT though. Uninstalling the TensorRT gets rid of the error message and it works as before.
How to get TensorRT working now? I got a RTX 3080 which is not even optimal for that but I presume it should work?!

God bless you in advance
Bananamax

**Comment by EtienneDosSantos** [comment]
**Issue Explanation:**

This issue is a recognized problem stemming from a bug in the installer. People are already working on a fix.

**Temporary Solution:**

In the meantime, you don't need to wait for the official fix. Please refer to this workaround detailed in [issue #27](https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/issues/27#issuecomment-1767570566). Following these steps should resolve the problem for you.

**Comment by Bananamax** [comment]
God bless you it might've worked. No more error message at least. However I dont see any TensorRT tab nor is there anything else than "None" or "Automatic" in the SD Unet dropdown menu. Under "installed" there is "Stable-Diffusion-WebUI-TensorRT" checked though.

**Comment by contentis** [comment]
Can you check the shell for any errors when launch web UI?

**Comment by Bananamax** [comment]
Launching Web UI with arguments:
No module 'xformers'. Proceeding without it.
[-] ADetailer initialized. version: 23.7.9, num models: 9
Loading weights [e6415c4892] from C:\ProgramData\Anaconda3\tortoise-tts\stable-diffusion-webui\models\Stable-diffusion\realisticVisionV20_v20.safetensors
Creating model from config: C:\ProgramData\Anaconda3\tortoise-tts\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Couldn't find VAE named vae-ft-ema-560000-ema-pruned.ckpt; using None instead
Applying attention optimization: Doggettx... done.
Textual inversion embeddings loaded(1): easynegative
Model loaded in 7.6s (load weights from disk: 0.7s, create model: 0.3s, apply weights to model: 5.6s, apply half(): 0.3s, move model to device: 0.5s, calculate empty prompt: 0.1s).
*** Error executing callback ui_tabs_callback for C:\ProgramData\Anaconda3\tortoise-tts\stable-diffusion-webui\extensions\Stable-Diffusion-WebUI-TensorRT\scripts\trt.py
    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\tortoise-tts\stable-diffusion-webui\modules\script_callbacks.py", line 153, in ui_tabs_callback
        res += c.callback() or []
      File "C:\ProgramData\Anaconda3\tortoise-tts\stable-diffusion-webui\extensions\Stable-Diffusion-WebUI-TensorRT\ui_trt.py", line 751, in on_ui_tabs
        choices=get_valid_lora_checkpoints(),
      File "C:\ProgramData\Anaconda3\tortoise-tts\stable-diffusion-webui\extensions\Stable-Diffusion-WebUI-TensorRT\ui_trt.py", line 536, in get_valid_lora_checkpoints
        return [
      File "C:\ProgramData\Anaconda3\tortoise-tts\stable-diffusion-webui\extensions\Stable-Diffusion-WebUI-TensorRT\ui_trt.py", line 539, in <listcomp>
        if v["version"] == get_version_from_model(shared.sd_model)
      File "C:\ProgramData\Anaconda3\tortoise-tts\stable-diffusion-webui\extensions\Stable-Diffusion-WebUI-TensorRT\ui_trt.py", line 26, in get_version_from_model
        if sd_model.is_sd1:
      File "C:\ProgramData\Anaconda3\tortoise-tts\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1614, in __getattr__
        raise AttributeError("'{}' object has no attribute '{}'".format(
    AttributeError: 'LatentDiffusion' object has no attribute 'is_sd1'

So this one here might be important?! "*** Error executing callback ui_tabs_callback for C:\ProgramData\Anaconda3\tortoise-tts\stable-diffusion-webui\extensions\Stable-Diffusion-WebUI-TensorRT\scripts\trt.py"

**Comment by Bananamax** [comment]
So its a ruse its not loading any tensorRT modules. What a shame
