### ISSUE TITLE
Error installing TensorRT extension on SD.NEXT

### ISSUE THREAD

**Issue by LankyPoet** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#8]
Using latest version on master branch of SD.NEXT:
11:09:56-340763 INFO     Version: app=sd.next updated=2023-10-14 hash=98bf24d7
                         url=https://github.com/vladmandic/automatic.git/tree/master

Added the extension, then saw an installer error. In my SDNEXT.log file I found the following:

`2023-10-17 11:10:36,666 | sd | DEBUG | installer | TensorRT is not installed! Installing...

C:\sdnext\venv\lib\site-packages\pytorch_lightning\utilities\distributed.py:258: LightningDeprecationWarning: `pytorch_lightning.utilities.distributed.rank_zero_only` has been deprecated in v1.8.1 and will be removed in v2.0.0. You can import it from `pytorch_lightning.utilities` instead.

  rank_zero_deprecation(

+--------------------- Traceback (most recent call last) ---------------------+

| C:\sdnext\extensions\_TensorRT\install.py:30 in <module>                    |

|                                                                             |

|   27         shared.opts["quicksettings_list"].append("sd_unet")            |

|   28         shared.opts.save(shared.config_filename)                       |

|   29                                                                        |

| > 30 install()                                                              |

|   31                                                                        |

|                                                                             |

| C:\sdnext\extensions\_TensorRT\install.py:8 in install                      |

|                                                                             |

|    5     if not launch.is_installed("tensorrt"):                            |

|    6         print("TensorRT is not installed! Installing...")              |

|    7         launch.run_pip("install nvidia-cudnn-cu11==8.9.4.25", "nvidia- |

| >  8         launch.run_pip("install --pre --extra-index-url https://pypi.n |

|    9         launch.run(["python","-m","pip","uninstall","-y","nvidia-cudnn |

|   10                                                                        |

|   11     # Polygraphy                                                       |

+-----------------------------------------------------------------------------+

TypeError: run_pip() got an unexpected keyword argument 'live'`

**Comment by GalaxyTimeMachine** [comment]
Same :(

**Comment by contentis** [comment]
This has never been tested with SD Next. And currently there are no plans to officially support it. But we're open to contributions.

**Comment by contentis** [comment]
It seems like this could be easily resolved on the SD.Next side by accepting kwargs. Or having API parity with AUTO1111.

See here: https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/blob/main/install.py#L8,L13,L19
