### ISSUE TITLE
Hooks for unet patching

### ISSUE THREAD

**Issue by ljleb** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#80]
I have implemented FreeU for the webui here:
https://github.com/ljleb/sd-webui-freeu

Some users noticed that it was not possible to use FreeU in conjunction with TRT:
https://github.com/ljleb/sd-webui-freeu/issues/36

FreeU replaces the `th.cat` that concatenates the backbone with the skip connections as input to each unet decoder block.

I've skimmed through the code but I can't find the unet forward function used by TRT, so I'm not sure what to patch. I tried debugging but I can't step into what appears to be the [actual unet forward call](https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/blob/4c2bcafd854f7bc74d3ca9c5c3c90112e9fe6e55/utilities.py#L454). So my first question is, how can I patch the concatenation logic for the decoder blocks when TRT is in use?

And I guess as a more general question, for any other extension, how can I patch any part of the unet forward function when TRT is in use? Is this not possible because the code is compiled?

**Comment by contentis** [comment]
The engine is compiled and can't be intercepted. I assume FreeU is a different Unet architecture / uses some magic in between the encoder and decoder connections?

**Comment by ljleb** [comment]
No magic, it's just a scalar for the backbone and a highpass filter for the skip connection, one of each for each stage of decoder blocks.

**Comment by ljleb** [comment]
I am suspecting this is not very practical, but if we could compile the engine into 2-3 components and then compose these blocks during inference, then arbitrary code could be inserted between the compiled components.

**Comment by drhead** [comment]
Thinking of alternatives for solving this -- would it be possible to simply bake the FreeU calculations into the ONNX graph with either pre-set values or accepting scalar inputs?  It's quite likely that a majority of people using FreeU will only have one set of settings they use for each model.

**Comment by ljleb** [comment]
Was this closed because FreeU was added or made possible in some way, or is this simply not planned?
