### ISSUE TITLE
 Error Code 3: API Usage Error

### ISSUE THREAD

**Issue by Hugs288** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#82]
[E] 3: [executionContext.cpp::nvinfer1::rt::ExecutionContext::validateInputBindings::2045] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::nvinfer1::rt::ExecutionContext::validateInputBindings::2045, condition: profileMaxDims.d[i] >= dimensions.d[i]. Supplied binding dimension [1,231,768] for bindings[2] exceed min ~ max range at index 1, maximum dimension in profile is 154, minimum dimension in profile is 77, but supplied dimension is 231.

i get that error for every step of an image being generated

the image generation itself is fine.

**Comment by aqunyawa** [comment]
Doubling that request, getting exactly same error.
Here are my TRT profiles, they are built specifically for the resolutions I use.

Profile 0

  | Min | Opt | Max
-- | -- | -- | --
Height | 512 | 512 | 768
Width | 512 | 512 | 768
Batch Size | 1 | 1 | 4
Text-length | 75 | 75 | 150

Profile 1

  | Min | Opt | Max
-- | -- | -- | --
Height | 768 | 1024 | 1024
Width | 768 | 1024 | 1024
Batch Size | 1 | 1 | 4
Text-length | 75 | 75 | 150

**Comment by algarci104** [comment]
Either the negative or positive prompts that you have are going above the 154 word limit. Lower the amount of words and it should stop popping up.

**Comment by aqunyawa** [comment]
> Either the negative or positive prompts that you have are going above the 154 word limit. Lower the amount of words and it should stop popping up. You could also create a custom engine with a higher text limit.

So as I understand it, this limit is for positive prompt + negative prompt, not for both prompts separately?

**Comment by CarlosATeixeira** [comment]
im having the same problem, but i have an engine with 400 token. It seems its always choosing Profile 0

**Comment by thejohnd0e** [comment]
I have the same problem - I can't get an image larger than 768 on one side

![Screenshot - 2024-01-13 06 29 28](https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/assets/115493464/33a2d228-52e8-4d26-a6d2-664346975095)

![Screenshot - 2024-01-13 06 34 03](https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/assets/115493464/5d92103e-6a0b-4307-8b4f-530209daf8c5)

**Comment by rinaldop** [comment]
Same for me. Solved after a change in the negative prompt (shorter...)
