### ISSUE TITLE
cpu and cuda:0 tensor mismatch for SDXL

### ISSUE THREAD

**Issue by aifartist** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#88]
Ubuntu 22.04.1 4090
A1111 1.6   Fresh version of this extension.
Building 1024x1024x1 engine works.
But trying an inference returns:

```
      File "/home/dwood/a1-231011/venv/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 125, in forward
        return F.linear(input, self.weight, self.bias)
    RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument mat1 in method wrapper_CUDA_addmm)
```

Diagnostic code shows:
```
input.is_cuda True
self.weight.is_cuda False
self.bias.is_cuda False
```
on the 409th F.linear call but trying to force them back is being ignored.

**Comment by aifartist** [comment]
It is NOT on the first call to F.linear but the 409th call after startup before I get:
input.is_cuda True
self.weight.is_cuda False
self.bias.is_cuda False

I tried some code that tests for this and force weight and bias back onto the GPU but the "to('cuda:0')" leaves is_cuda false.  Quite strange.

I recall some dim memory of having a to('cuda:0') be ignored before and don't recall how I fixed it.

**Comment by aifartist** [comment]
VERY interesting.  In timm/models/layers/lineary.py which is unlikely even involved with this I find the following. 

```
class Linear(nn.Linear):
    r"""Applies a linear transformation to the incoming data: :math:`y = xA^T + b`

    Wraps torch.nn.Linear to support AMP + torchscript usage by manually casting
    weight & bias to input.dtype to work around an issue w/ torch.addmm in this use case.
    """
    def forward(self, input: torch.Tensor) -> torch.Tensor:
        if torch.jit.is_scripting():
            bias = self.bias.to(dtype=input.dtype) if self.bias is not None else None
            return F.linear(input, self.weight.to(dtype=input.dtype), bias=bias)
        else:
            return F.linear(input, self.weight, self.bias)
```

**Comment by KappaMund** [comment]
A similar problem after updating the extension to version 4c2bcaf

**Comment by KappaMund** [comment]
@aifartist The problem was in the "--medvram-sdxl" in webui-user.bat file.

**Comment by aifartist** [comment]
> @aifartist The problem was in the "--medvram-sdxl" in webui-user.bat file.

I'm on Ubuntu and not Windows.
In my v1.6.0 A1111 in any of the windows or Linux shell/bat files there is no --medvram or --medvram-sdxl setting used.  I only see a comment in the changelog that you can use it but I am not.

**Comment by aifartist** [comment]
When I did a quick try of this I missed the A1111 "dev branch" instruction.  Given it worked so well for SD1.5 models(74.5 it/s and .313 gen times) I was locked in and blind.  Then I took another look and Whoops.  Sorry.
