### ISSUE TITLE
Consistent Selection of Profile 0 Across Various Scenarios

### ISSUE THREAD

**Issue by EtienneDosSantos** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#95]
**Observation:** 
  - `Profile 0` is consistently selected across various scenarios, be it with different numbers of prompt tokens or whether the engine is static or dynamic. 

**Instances:**
  - In one checkpoint, `Profile 0 is` set as the default engine.
  - In another, it is defined as a static shaped engine.

**Question:**
  1. Has anyone observed a profile other than `Profile 0` being utilized?
  2. What is the actual effect of varying text-length values on the generated engines?

**Comment by contentis** [comment]
Please see: https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/issues/65#issuecomment-1771065170
I hope this answers your question.

**Comment by EtienneDosSantos** [comment]
I see, thx a lot!
